### ISSUE TITLE
Add support for Lua (WoW)

### ISSUE THREAD

**Issue by Gethe** [rgbkrk/atom-script#1008]
```
Command not configured for Lua (WoW)!

^C
```

It's the same as the standard Lua grammars, but with some added highlighting support for the World of Warcraft AddOn API. The package for it is under [language-lua-wow](https://atom.io/packages/language-lua-wow).

**Comment by nixel2007** [comment]
Can Lua (WoW) be runned via simple `lua` interpreter?

**Comment by Gethe** [comment]
Yeah it can

**Comment by nixel2007** [comment]
:ship: in 3.8.2!
