### ISSUE TITLE
python output issue with Chinese

### ISSUE THREAD

**Issue by rzabb** [rgbkrk/atom-script#1014]
code：
#coding=utf-8
print("你好")

putout：
![qq 20160723163313](https://cloud.githubusercontent.com/assets/20595330/17076989/662e4202-50f3-11e6-826e-7a1feccddba8.png)

- system: windows 7-64

- python：3.5.2

I  use **`# coding=utf-8`**,but it doesn't work
So I post here to seek helps.

**Comment by nixel2007** [comment]
https://github.com/rgbkrk/atom-script/issues/590

**Comment by rzabb** [comment]
thanks
