### ISSUE TITLE
{FILE_ACTIVE_NAME_BASE} does not work

### ISSUE THREAD

**Issue by econwang** [rgbkrk/atom-script#1027]
hi, I try the run with option, while {FILE_ACTIVE_NAME} works well, {FILE_ACTIVE_NAME_BASE} does not work as expected, for example, {FILE_ACTIVE_NAME_BASE}.tex results in ..tex

**Comment by stefanprobst** [comment]
Doesn't work for me either.
I changed line 95 in lib/runner.coffee to

`arg = arg.replace(/{FILE_ACTIVE_NAME_BASE}/g, path.basename(codeContext.filename, path.extname(codeContext.filename)))`

which seems to work.

**Comment by nixel2007** [comment]
@stefanprobst good news! could you make a PR with this changes (to include your name in commit history :) ?

**Comment by stefanprobst** [comment]
@nixel2007 well, as I don't know much about programming and really only use atom for markdown writing (and atom-script to run pandoc), how would I make a PR? Like this?

`git clone https://github.com/rgbkrk/atom-script.git`
change lib/runner.coffee
```
git commit
git push
```

**Comment by nixel2007** [comment]
@stefanprobst you can just click on edit button here https://github.com/rgbkrk/atom-script/blob/master/lib/runner.coffee
make an edit and click on `propose file changes` at the bottom (make sure, the `Create a new branch for this commit and start a pull request.` option is selected
