### ISSUE TITLE
No Run Options

### ISSUE THREAD

**Issue by sogen** [rgbkrk/atom-script#1063]
Installed it and want to specify Python3, but don't see Run Options as mentioned in the Readme:

![screen shot 2016-08-30 at 8 42 40 am](https://cloud.githubusercontent.com/assets/2784323/18091331/d7b6bd5c-6e8d-11e6-8062-eebc2b1f5722.png)

**Comment by nixel2007** [comment]
Use the "Configure Script" menu

**Comment by nixel2007** [comment]
Fixed in readme. Thanks!
