### ISSUE TITLE
Add Line Number Based support for JavaScript

### ISSUE THREAD

**Issue by keemy** [rgbkrk/atom-script#1068]
##### Platform: `win32`
Atom: 1.10.0
script: 3.9.0
---

Not sure if I am doing something wrong the readme says line based support should work for javascript but it doesn't work for me.

running just `console.log("hello");`
![image](https://cloud.githubusercontent.com/assets/626229/18222400/c24e2174-714b-11e6-8972-07272f25becd.png)

**Comment by iamolivinius** [comment]
Keep in mind that there is a difference between "selection based" and "line number based" execution. As far as I can see script supports "selection based" execution only.

To execute a selection hit `ctrl+shirt+b` on Linux and `cmd+b` on Mac

**Comment by keemy** [comment]
Ah my bad must have misread.
Thanks I'll close this.
