### ISSUE TITLE
Add support for MIPS Assembler

### ISSUE THREAD

**Issue by Olian04** [rgbkrk/atom-script#1070]
Could you add support for [MCB32](https://github.com/is1200-example-projects/mcb32tools/releases/) mips assembler?

_(MIPS is a popular teaching variant of assembler)_

**Comment by nixel2007** [comment]
Does it have a dedicated atom grammar?

**Comment by Olian04** [comment]
@nixel2007  like [this one](https://atom.io/packages/language-mips)?

**Comment by nixel2007** [comment]
@Olian04 yeah, it's good.

Could you provide some command to run current file through MCB32? Lets say, that the executable is in the PATH already.

**Comment by Olian04** [comment]
@nixel2007 
(I'm still rather new to MCB32)
But [this project](https://mega.nz/#!DAoE0Dgb!RocrVgaRHs7DGSh-jp2r7ZyYq13HuSt-peValqiTSA4) works.

And this is the way I've been using it is:
0. Install MCB32
1. Call `. /opt/mcb32tools/environment`
2. Cd to `file path`
3. Call `make`

**Comment by Olian04** [comment]
@nixel2007 
Better aswere this time: 
You can interpret MIPS wither using [Mars](http://courses.missouristate.edu/kenvollmar/mars/) -> `java -jar mars.jar nc <input-file>`, or [SPIM](http://spimsimulator.sourceforge.net/) -> [spim, xspim, pcspim](http://spimsimulator.sourceforge.net/SPIM_command-line.pdf).
