### ISSUE TITLE
Problem with java

### ISSUE THREAD

**Issue by Akumetsu-Dev** [rgbkrk/atom-script#1104]
![captura de pantalla 4](https://cloud.githubusercontent.com/assets/7697566/19293454/6aeaeaaa-8ff2-11e6-8608-e98a7096b803.png)
![captura de pantalla 6](https://cloud.githubusercontent.com/assets/7697566/19293474/b1d9cf12-8ff2-11e6-8217-c85eda31dc45.png)
![captura de pantalla 7](https://cloud.githubusercontent.com/assets/7697566/19293476/b3ce53e2-8ff2-11e6-83f8-c42bcecd94a0.png)
![captura de pantalla 9](https://cloud.githubusercontent.com/assets/7697566/19293477/b61e205a-8ff2-11e6-9d3a-ffef81fd651b.png)

**Comment by andyrichardson** [comment]
There's nothing wrong with your PATH variable as *javac* is running fine. In your first shot, the folder of the above project is highlighted and I suspect that is where the issue is.

Try opening the file on its own without any other projects loaded.

**Comment by sagarsumit03** [comment]
hi,

Same issue. getting the below error. Please advise.

'javac' is not recognized as an internal or external command,
operable program or batch file.
[Finished in 0.102s]

**Comment by andyrichardson** [comment]
> Same issue. getting the below error.

Completely different issue. You need to configure your environment variables appropriately.

**Comment by sagarsumit03** [comment]
got the error. I was mistakenly setting jre path instead of jdk. thank you!

now i am able to compile.

**Comment by Akumetsu-Dev** [comment]
well, i reformatted the system and is working, so this post can be closed. ty for the help.
