### ISSUE TITLE
Script wont work for the includes method in Javascript!?

### ISSUE THREAD

**Issue by harryttd** [rgbkrk/atom-script#1109]
Hey guys.

Does anyone have any idea how to fix this issue?

Example:
```
console.log([1,2,3].includes(2));
```
 I get an error in script saying: 
```
console.log([1,2,3].includes(2));
                    ^
TypeError: [1,2,3].includes is not a function
```

Thanks!

**Comment by andyrichardson** [comment]
Your version of Node does not support the includes prototype method. You'll need to update. https://github.com/nodejs/node/issues/5715

**Working proof:**
![screenshot from 2016-10-16 22-39-48](https://cloud.githubusercontent.com/assets/10779424/19421136/7d0b6c34-93f1-11e6-975a-aee229d87c54.png)

**Comment by harryttd** [comment]
Thank you!

**Comment by andyrichardson** [comment]
Happy to help. Please close the issue :+1:
