### ISSUE TITLE
GrammarUtils.Nim.projectDir Returns Incorrect Project Directory

### ISSUE THREAD

**Issue by andyrichardson** [rgbkrk/atom-script#1118]
## Replication

1. Open a project folder
2. Create a subfolder inside the project
3. Create a test file inside said subfolder
4. Call GrammarUtils.Nim.ProjectDir(context.filepath) from your testfile

**Expected result:** Project folder directory is returned
**Actual result:** Subfolder directory is returned

## Example
![screenshot from 2016-10-24 13-42-40](https://cloud.githubusercontent.com/assets/10779424/19646084/cd02dfe8-99ef-11e6-80d4-f442f95b187d.png)
_Function call._

![screenshot from 2016-10-24 13-38-10](https://cloud.githubusercontent.com/assets/10779424/19646039/967f05e6-99ef-11e6-9834-1be8731cceaa.png)
_Result of function call (see console). Note project folder on the left._

## Resulting Issues
#1107 doesn't work as expected. Java compilation is no longer functional.

**Comment by nixel2007** [comment]
You can use [this code](https://github.com/rgbkrk/atom-script/blob/62a1f65af692d3b9fdc799545665ade0fb38e207/lib/runner.coffee#L116) to get the current project dir.

**Comment by andyrichardson** [comment]
Thanks @nixel2007. There'll be a pull request soon modularizing the Java preparation scripts - it seems as though I misunderstood the structure of the _grammar-utils_.
