### ISSUE TITLE
Add support for Batch File

### ISSUE THREAD

**Issue by leifmariposa** [rgbkrk/atom-script#1131]
If I have https://atom.io/packages/language-batchfile installed I get this error, but then I found out that it works if I use package https://atom.io/packages/language-batch instead.

Also if I added the following to grammars.coffee it works with package https://atom.io/packages/language-batchfile.
  'Batch File':
    "File Based":
      command: "cmd.exe"
      args: (context) -> ['/q', '/c', context.filepath]

Maybe add this to grammars.coffee? Or point it out in the documentation?
Br
Leif Persson

**Comment by andyrichardson** [comment]
Support for batch files have been discussed already in #470. Please continue the discussion over there and feel free to submit a pull request if you have a solution to the issue.
