### ISSUE TITLE
Add support for HTML

### ISSUE THREAD

**Issue by youssef34** [rgbkrk/atom-script#1141]
It shows up and says error command not configured 
add an issue on GitHub or send your own pull request 
I don't know how to run my code in the browser

**Comment by andyrichardson** [comment]
There are around 60 closed issues regarding HTML with this package. HTML is not a scripting language and therefore will not work with this package.

If you want to preview your HTML in atom, there are many packages to do this - https://atom.io/packages/atom-html-preview
