### ISSUE TITLE
Problem with building in Atom

### ISSUE THREAD

**Issue by Grinzzly** [rgbkrk/atom-script#1158]
No matter what I try to launch by using script pack the same message appears

"node" �� ����� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� �������� 䠩���.
[Finished in 0.092s]

or

"python" �� ����� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� �������� 䠩���.
[Finished in 0.306s]

P. S. the same code-error was given to me by linter-pep 8
![noi3qkptgxg](https://cloud.githubusercontent.com/assets/23696154/20602426/2d45688a-b26e-11e6-8a9d-cee13ac19aea.jpg)
![q27vnl5qyi0](https://cloud.githubusercontent.com/assets/23696154/20602427/2d5b3322-b26e-11e6-8bee-97653d45f5f5.jpg)

Found possible solution here http://stackoverflow.com/questions/28995790/python-doesnt-work-in-atom
But it dosen't work in my case (I add line to path and notihng happend)

**Comment by nixel2007** [comment]
Is `python` and `node` in your PATH? 
What operating system do you have?

**Comment by Grinzzly** [comment]
Yes, they are. The path to pythons and nodes files in there. Windows 10 x64

**Comment by nixel2007** [comment]
Can you check please if binary is named python and not python3?

**Comment by Grinzzly** [comment]
It is definitely right

![untitled-2](https://cloud.githubusercontent.com/assets/23696154/20614637/f7adad9e-b2e1-11e6-9f0d-f84fcf29e868.jpg)

**Comment by nixel2007** [comment]
1. Try to open atom from command line `atom .` in your project dir and run script. 
2. Try to add python to your system environment variables (as I can see, you add it to your local/user variables) 
3. Try to add slash at the and (I don't sure it can help, but I can't ignore stackoverflow.com :D)

**Comment by Grinzzly** [comment]
How do I set system environment variables in Windows 10? There is where I'm done it before:
**“Advanced system settings” → “Environment Variables”** and you mean to tell that is only local ones? So what about whole system?

**Comment by Grinzzly** [comment]
Wow! The one aaditional helped with console. 👍 

But not witn linter-pep8 
![untitled-2](https://cloud.githubusercontent.com/assets/23696154/20614832/05709b88-b2e4-11e6-9a30-ff826757d678.jpg)

**Comment by nixel2007** [comment]
Doesn't it need to have pep8 globally installed? Is pep8 some command line utility? In this case linter-pep8 only parses the command run result. Can you check the linter-pep8 docs for this?

**Comment by Grinzzly** [comment]
Ah. Nevermind. I just found another linter for python (linter-pylint) and consider problem as a solved one.
Appreciate your help.

З. Ы. Питон в Атоме такой...питон
