### ISSUE TITLE
Running R scripts in Atom

### ISSUE THREAD

**Issue by Vinay-Iyer** [rgbkrk/atom-script#1159]
Hi There, 

Need some help in running R codes inside Atom. `r-exec` doesn't seem to be working any longer. I see this when installing. 

![r-exec](https://cloud.githubusercontent.com/assets/10484243/20627242/0e8b33f0-b31f-11e6-8e59-b372a34f71b0.PNG)

Also atom doesnt seem to recognize .r files like it does for .py. 

Any fix for this. ? Appreciate your help. 

Thanks,
Venkat

**Comment by nixel2007** [comment]
You should be able to run R through this package, if you have Rscript installed https://github.com/rgbkrk/atom-script/blob/master/lib/grammars.coffee#L657

**Comment by nixel2007** [comment]
Also you need to install some syntax package for R

**Comment by Vinay-Iyer** [comment]
ok cool. Syntax package installed. So that works now. 

When running 'Rscript' it says. 

![r-script](https://cloud.githubusercontent.com/assets/10484243/20631763/c4cc8d12-b338-11e6-8002-fbb49dbb48e6.PNG)

Any fix to this ?

**Comment by nixel2007** [comment]
Looks like you need to install some utils package and add Rscript to your path http://stat.ethz.ch/R-manual/R-devel/library/utils/html/Rscript.html
But I don't sure it can be runned on Windows. 
If you could check it or find any other way to run R at win, I'll glad to help implement it support
