### ISSUE TITLE
Add support for JavaScript (JSX)

### ISSUE THREAD

**Issue by MrCooper42** [rgbkrk/atom-script#1162]
Is there a conflicting package known or a work around?

**Comment by andyrichardson** [comment]
I can't see why you would want to run JSX inside of a terminal. Surely you'll be running a server/testing platform which compiles the JSX before execution?

**Comment by danielbayley** [comment]
@MrCooper42 This is implemented [here](https://github.com/rgbkrk/atom-script/blob/master/lib/grammars/javascript.js#L36).
