### ISSUE TITLE
Convert codebase to JavaScript

### ISSUE THREAD

**Issue by rgbkrk** [rgbkrk/atom-script#1171]
Admittedly, most of the reason I don't come back to maintaining this project is that I started it in CoffeeScript in a time before I knew JavaScript well. If it was in JavaScript I'd probably tackle cleaning up the more pesky bits of this code base. Instead, I've been focused on other projects.

It would be super cool to have the code base be modernized.

**Comment by nixel2007** [comment]
You can just transpile the coffeescript to javascript - manually with the `coffee` compiler or with some online tool
