### ISSUE TITLE
Java Compile error

### ISSUE THREAD

**Issue by 20031004** [rgbkrk/atom-script#1200]
sorry for my English. I am Foreigner.

OS win10 64bit LG
I want to compile this simple program. 
I install Script and press ctrl+shift+b but is isn't working.
But, script added JAVA.class. 

JAVA.java
`public class JAVA{
  public static void main(String[] args) {
    System.out.println("d");
  }
}
`
And error is appeared.
����: �⺻ Ŭ���� JAVA��(��) ã�ų� �ε��� �� �����ϴ�.
![default](https://cloud.githubusercontent.com/assets/24790120/21585445/9945efa6-d103-11e6-9fc2-26958be60a3c.PNG)
NO problem about my environment variables.
classpath-%JAVA_HOME%\lib;
JAVA_HOME-C:\Program Files\Java\jdk1.8.0_77;
Path-%JAVA_HOME%\bin;

please help me.

**Comment by andyrichardson** [comment]
Hi there, I'm looking into your issue right now. The steps I've taken to recreate the bug were as follows:

- Created a JAVA.java file in a project folder

- Added said project folder to Atom

- Inputted class and main method into JAVA.java

- Saved file

- Executed script (CTRL+SHIFT+B)

The result was a command line application printing text.

**Tasks for you**
Can you please follow the steps above and tell me if the error persists.
Can you please open command prompt, type 'java' and hit enter - post the results here.

**Bonus tips**
I'm assuming you're pretty new to Java so here's some quick advice. The typical class naming conventions use CamelCase. So if your application is a test, you would want to give the class a name such as _MyTest_ or simply _Test_. Variables are used in a similar fashion only the initial character is lower case. An instance of _MyTest_ might be called _myTestInstance_.

**Comment by 20031004** [comment]
i write "java" in command prompt, and...
![default](https://cloud.githubusercontent.com/assets/24790120/21598406/eb8ac678-d19f-11e6-8fb1-81cbe1335bf9.PNG)
(I'm Korean)
Also I write javac (java compiler),
![default](https://cloud.githubusercontent.com/assets/24790120/21598454/996352ec-d1a0-11e6-954b-9305cb4bcb53.PNG)

**Comment by 20031004** [comment]
and I change classpath to '.'

**Comment by 20031004** [comment]
oh I solve it! Camelcase! That is the problem. thanks!

**Comment by 20031004** [comment]
close #1200

**Comment by 20031004** [comment]
resolve #1200

**Comment by andyrichardson** [comment]
I suspect the issue wasn't related to the case of your class as I was able to run your example fine. Anyhow, glad to hear your issue was solved.
