### ISSUE TITLE
Javac : File not found

### ISSUE THREAD

**Issue by 20031004** [rgbkrk/atom-script#1206]
(sorry, I'm a Foreigner, Not good at English.)
OS: windows 10, 64bit
I compile java program with script, and is working.
But There is one problem. I want to compile java program build in Eclipse.
EXAMPLE - my Eclipse project path is D:\project\java_tutorials.
I open D:\project\java_tutorials\src\org\opentutorials\javatutorials\compare\EqualDemo.java .
because I make package "org.opentutorials.javatutorials.compare" and make Java class named "EqualDemo" at Eclipse.
`package org.opentutorials.javatutorials.compare;

public class EqualDemo {

	public static void main(String[] args) {
		System.out.println(1 == 2); // false
		System.out.println(1 == 1); // true
		System.out.println("one" == "two"); // false
		System.out.println("one" == "one"); // true

	}

}
`
But Error is appeared.
![default](https://cloud.githubusercontent.com/assets/24790120/21708528/f3f2d1e6-d41c-11e6-99c8-1ee021518277.PNG)

One Interest thing, When I make this sample in D:\project\java_tutorials, is working.
![image](https://cloud.githubusercontent.com/assets/24790120/21708554/5287149c-d41d-11e6-85a8-cf20f49a03cd.png)

that means no PROBLEM in my environment variables.
Help me to solve this Error....PLEASE

**Comment by 20031004** [comment]
Oh I solve

**Comment by andyrichardson** [comment]
Packages aren't currently supported. See #1201 for support progress

**Comment by cyciopes** [comment]
hi @20031004 , may I know how do you solve the problem?  I have same issue. Thanks.

**Comment by amankriet** [comment]
Same Issue with me too... please help!
