### ISSUE TITLE
[Push request]: add "do" language -for Stata- (here is the code)

### ISSUE THREAD

**Issue by rhoconlinux** [rgbkrk/atom-script#121]
I edited the file <code>grammars.coffee</code> with this:
```coffee
  do:
    "Selection Based":
      command: "xstata-se"
      args: (code)  -> [' do ', code]
    "File Based":
      command: "xstata-se"
      args: (filename) -> [' do ',filename]
```
that allows Atom to run stata <code>.do</code> files. The language definitions are in my repo http://git.io/gkctpQ.

**Comment by nickeubank** [comment]
@erran @rhoconlinux Hello all -- what's the status of this? Look like an attempt allow Stata to run dofiles, but seems it just got hung. I'm new to Atom, but with a little guidance would be happy to take this up and integrate.
