### ISSUE TITLE
C++ cin [not working]

### ISSUE THREAD

**Issue by CamrynD** [rgbkrk/atom-script#1212]
The Output window will not allow a ".cpp" file to take inputs from the user.

an example:
`cin >> anything;`
The Code stops there and waits for input.

works fine with python. Would be great if this could be fixed, this Package saves a lot of much time.

**Comment by rgbkrk** [comment]
Thank you for reporting. We don't support stdin and no one is working on supporting it. Closing as duplicate of #385.
