### ISSUE TITLE
 Command not configured for JavaScript (JSX)!

### ISSUE THREAD

**Issue by matthewbryancurtis** [rgbkrk/atom-script#1226]
Noticed some people reporting this issue, but the descriptions seem different than what I'm trying to do. I get the error "Command not configured for JavaScript (JSX)!" whenever I run ANY JavaScript code - more often than not without JSX.

``` JavaScript
console.log("Hello World");
// Command not configured for JavaScript (JSX)!

return "Hello";
// Command not configured for JavaScript (JSX)!
```

This hasn't always been the case, atom-script had been working fine for little things like this in the past.

**Comment by danielbayley** [comment]
@matthewbryancurtis This is implemented [here](https://github.com/rgbkrk/atom-script/blob/master/lib/grammars/javascript.js#L36).
