### ISSUE TITLE
Add support for JavaScript ES6

### ISSUE THREAD

**Issue by Akberovr** [rgbkrk/atom-script#1255]
When I pressed cmd-i ,this error is shown.Could anybody give me hand with this?

<img width="1090" alt="screen shot 2017-02-23 at 18 11 31" src="https://cloud.githubusercontent.com/assets/20392064/23262296/a72ce412-f9f3-11e6-9087-bc3b6e69fb5e.png">

**Comment by danielbayley** [comment]
@Akberovr This is implemented [here](https://github.com/rgbkrk/atom-script/blob/master/lib/grammars/javascript.js#L35).
