### ISSUE TITLE
ReferenceError: document is not defined.

### ISSUE THREAD

**Issue by srseven** [rgbkrk/atom-script#1256]
my code is:

`document.getElementById('example').innerHTML = 'Hello World';`

I run this and `script` displays this error.

**Comment by andyrichardson** [comment]
You can't run this code outside of a browser. This is client side JavaScript that you're trying to run inside a Node.js environment.

**Comment by srseven** [comment]
is there a way to access DOM inside atom as atom has built-in dev tools. i open dev tools in atom but it is focused on the atom editor rather than the active file.
