### ISSUE TITLE
How Do I Change the PATH for Script and Runner

### ISSUE THREAD

**Issue by MPresman** [rgbkrk/atom-script#1292]
Installed the Script package in order to run javascript scripts.

Won't run because the path it returns is my default Python3 IDE for some reason?
When I try running python code, it works obviously.

How do I change the path so it runs javascript code?
And also, where is the javascript path located.

e.g. want to run
console.log("Hello world");

-------------------------
System Specs
Mac OSX Sierra
Just downloaded Atom an hour ago.
-------------------------

--------------------------
TRACKBACK
Unable to run
node

Did you start Atom from the command line?
atom .

Is it in your PATH?
PATH: //anaconda/bin://anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/michaelpresman/Documents/Python/Path:/Library/Frameworks/Mono.framework/Versions/Current/Commands://anaconda/bin
----------------------------------------
I've tried running from terminal, finding the config file for this package and yet I can't get it to work.

**Comment by rgbkrk** [comment]
By any chance do you use `nvm`?

**Comment by MPresman** [comment]
Node Version manager?
No, I am not.

**Comment by MPresman** [comment]
edit: Just opened the script package and run every language in there from bash ruby to bash and hey all work in printing their message e.g. hello world or hello php, except for the longrun.js file
which is suppose to run a javascript code

this is some sick joke lol.

**Comment by MPresman** [comment]
please close this thread
i had node downloaded in a very wrong folder.
just needed to uninstall node via terminal
and reinstall it
