### ISSUE TITLE
Add support for YAML

### ISSUE THREAD

**Issue by sirbijan** [rgbkrk/atom-script#1305]
Apparently there is no support for Command in a *.yaml file.

**Comment by rgbkrk** [comment]
What are you expecting a yaml file to do?

**Comment by sirbijan** [comment]
I initially wanted to run beautify on it. If memory helps, after pressing Cmd-Shift-P, I got this automatic message and a link to github to create this issue! Now that I hit Cmd-Shift-P, the command palette does appear! Magic
