### ISSUE TITLE
font size is too small....

### ISSUE THREAD

**Issue by budheswarbaghel** [rgbkrk/atom-script#1352]
please! give the option to change the font size.

**Comment by budheswarbaghel** [comment]
Make it as it is on sublime text.

**Comment by stevenkkim** [comment]
I had the same problem too. For the time being, I just decided to override the CSS.

1) Go to Settings
2) Click on "Open Config Folder"
3) Open "styles.less"
4) Add:

```
div.panel-body.padded pre {
  font-family: Inconsolata, sans-serif; // set to whatever font you want
  font-size: 16px; // set to whatever font size you want
}
```

Hope this helps.
