### ISSUE TITLE
What is node

### ISSUE THREAD

**Issue by XtremePro** [rgbkrk/atom-script#1383]
When I run the code with Script it says node is not reconized. What does this mean?

**Comment by rgbkrk** [comment]
Node is a javascript runtime that you can run on your local machine or a server. If you're wanting to run javascript in atom script, it's the runtime you'll need to install.

nodejs.org

**Comment by XtremePro** [comment]
ok i installed it but how to connect it to Atom.io?

**Comment by rgbkrk** [comment]
What happens when you run a script using `script:run` now?
