### ISSUE TITLE
.rb files trying to run with rails instead of ruby

### ISSUE THREAD

**Issue by EternalPractice** [rgbkrk/atom-script#1425]
This functionality worked as of 2017/9/18 at 5:00 PM EDT, but with a recent update .rb files started trying to run in rails instead of ruby.

**Comment by JohnCoates** [comment]
Just had this problem, but it was with Atom itself detecting a .rb file as Ruby on Rails. I fixed it by clicking on the bottom where it says Ruby on Rails and selected Ruby instead.

**Comment by EternalPractice** [comment]
That fixed the issue.  Thanks!
