### ISSUE TITLE
Unabel to run 'babel-node'

### ISSUE THREAD

**Issue by GarenLiang** [rgbkrk/atom-script#1436]
![snip20170928_1](https://user-images.githubusercontent.com/15516507/30929898-947922e0-a385-11e7-9bae-fdb484cf904f.png)

**Comment by GarenLiang** [comment]
Have solved it with  **npm install -g babel-cli**

**Comment by beneon** [comment]
this work for me only once, after restart it doesn't work again.

**Comment by GarenLiang** [comment]
Really?I will test it later.

**Comment by GarenLiang** [comment]
I have tried it again.It works well in my Mac.

**Comment by ksuzushima** [comment]
I've got the same problem.
So I tried to solve with your way, but I got [this information](https://babeljs.io/docs/usage/cli/).

> Note: Since it's generally a bad idea to run Babel globally you may want to uninstall the global copy by running npm uninstall --global babel-cli.

What should I do for ? I need your idea.

**Comment by GarenLiang** [comment]
Hey,it works well in my laptop.If you have trouble with babel-cli.I think you can use other ways to solve it.Because lack of the **babel-node** module in your Atom or laptop.After get **babel-node** module.I think it will work.At the same time, check you Nodejs version.My version is v8.2.1.Also I installed **language-babe**l in my Atom.

**Comment by beneon** [comment]
There is too much global package install in the machine that generate this problem, maybe re-installing node would solve it.
Also, I recently found that the hydrogen plugin that utilizes jupyter to run python also got javascript kernel available, along with many other language support. Maybe it also worth trying.

**Comment by danielbayley** [comment]
@GarenLiang @beneon @ksuzushima This has now been addressed in fc84ded7dad08466923071e6d6e4370aa6a36789, and should 'just work' by using the preconfigured Babel setup in this package instead of having to set it up locally every time or worse, globally.

**Comment by ksuzushima** [comment]
@danielbayley Thank you so much. It works fine!

**Comment by GarenLiang** [comment]
Cool.🎉🎈✨

**Comment by mrichmond** [comment]
@danielbayley Is there a way to use my local project .babelrc and bin to run babel instead? I have extra plugins in my babel settings (babel-plugin-transform-object-rest-spread) that I want to use. language-babel and source-preview seem to do this by default... I get errors when running my code using atom-script with the default babel settings when I have object spread operator in my code.
