### ISSUE TITLE
Can't run JavaScript

### ISSUE THREAD

**Issue by jmangz** [rgbkrk/atom-script#1444]
`
Unable to run

babel-node
Did you start Atom from the command line?

  atom .
Is it in your PATH?

PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

I installed latest Node.js already. I saved the file as .js, I've tried running atom with Terminal.

**Comment by danielbayley** [comment]
@jmangz This has now been addressed in fc84ded7dad08466923071e6d6e4370aa6a36789, and should 'just work' by using the preconfigured Babel setup in this package instead of having to set it up locally every time or worse, globally.

**Comment by jmangz** [comment]
@danielbayley Thanks so much.
