### ISSUE TITLE
In windows, atom-script run /bin/bash 

### ISSUE THREAD

**Issue by insight1111** [rgbkrk/atom-script#1449]
environment:
OS: windows10 64bit
atom: 1.21.0
atom-script: 3.18.0
try to run: node(js) script

atom-script before(v3.16.0) in windows, worked correctly.
but v3.18.0, run in windows, get error below.

```
/bin/bash: C:\projects\harasanshin-homepage\test.js: そのようなファイルやディレクトリはありません(<- written in japanese, it means, no such as file or directry...sorry, I'm Japanese)
/bin/bash: node: コマンドが見つかりません(<- no command found)
```

it probably use /bin/bash. but windows don't have /bin/bash.
how to run correctry use cmd or powershell?
atom-script has not such options.

**Comment by danielbayley** [comment]
@insight1111 Fixed in #1451.
