### ISSUE TITLE
Won't work with python.

### ISSUE THREAD

**Issue by tazim04** [rgbkrk/atom-script#1520]
For some reason, it won't run python for me. I tried to run a program, but it gave this message: 'python' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jparet** [comment]
Stupid suggestions but:
- Is python installed on your computer ?
- Is the python executer included in your PATH ?

**Comment by phenomvenom** [comment]
Hi... I have the same problem but i dont know how to check if it is included in my path. Can you help me please ?

**Comment by jparet** [comment]
From https://wiki.python.org/moin/BeginnersGuide/Download:
First of all check that you don't already have Python installed by entering python in a command line window.

**Comment by jparet** [comment]
A solution was found in #1609 so I'm closing this thread ;)
