### ISSUE TITLE
Add support for LaTeX

### ISSUE THREAD

**Issue by MaruPr** [rgbkrk/atom-script#154]

**Comment by Alghamdi** [comment]
:+1:  +1

**Comment by andya9** [comment]
+1
Probably we would want to run: latexmk [options] masterfile.tex 
(we often work  on split .tex files referring to one .tex masterfile)

**Comment by Alghamdi** [comment]
@andya9 why not compiling currently opened file, which if referred to your main file will compile everything properly (e.g. `%!TEX root = masterfile.tex`).

**Comment by andya9** [comment]
@Alghamdi Yes, this is what I meant: the package reads the magic comment with the path of masterfile and sends to latexmk the path of masterfile instead of the path of current file.

**Comment by MrAdam** [comment]
Would be nice with LaTeX support :+1:
