### ISSUE TITLE
Feature Request: Output Auto Scroll

### ISSUE THREAD

**Issue by ygbr** [rgbkrk/atom-script#156]
It would be nice if the output console scrolls automatically with the text.

Scroll locks if the user scrolls up and return to auto if the user goes to the end of the script output (cursor).

Specially good for scripts that keep outputting their logs.

**Comment by erran** [comment]
This was fixed by https://github.com/rgbkrk/atom-script/pull/287 which was released in [v2.18.0](https://github.com/rgbkrk/atom-script/releases/v2.18.0).
