### ISSUE TITLE
Problem with PATH.

### ISSUE THREAD

**Issue by phenomvenom** [rgbkrk/atom-script#1609]
Hi. I think i made a mistake installing atom first and then python (2.7). I just know this error runs everytime i try to run a code:

'python' is not recognized as an internal or external command,
operable program or batch file.
[Finished in 0.091s]
'python' is not recognized as an internal or external command,
operable program or batch file.
[Finished in 0.109s]

Im trying to find solution on google for over an hour now so i would be really happy if someone helped me. I found that i need to change PATH but i dont know how. And... To be clear i am begginer with programming n stuff, just so you know.

**Comment by jparet** [comment]
Hi @phenomvenom if you are on Windows, maybe I could help you !

**Comment by phenomvenom** [comment]
Yes i am.

**Comment by jparet** [comment]
OK, so try to get the python path corresponding to your installation and add it to the Windows PATH following one of these instructions: https://www.computerhope.com/issues/ch000549.htm

Example: my python is on C:\Python and my Windows PATH looks something like
C:\Python\Scripts\;C:\Python\;C:\Users\Joffrey\AppData\Local\atom\bin;C:\Users\Joffrey\AppData\Local\GitHubDesktop\bin
Do not forget to separate paths with a semicolon.

**Comment by phenomvenom** [comment]
Should i put in path with executable or just folder ?... "C:\Python27\python.exe" or "C:\Python27\" ?

**Comment by phenomvenom** [comment]
Now it looks like this: C:\Python27\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0;

**Comment by jparet** [comment]
Just the folder. Now try to enter python in a command line window.

**Comment by phenomvenom** [comment]
I think it works, but now i got error that is something wrong about the code 😃...

**Comment by jparet** [comment]
:+1:
