### ISSUE TITLE
Script not finding my path on Windows 8

### ISSUE THREAD

**Issue by ron-md** [rgbkrk/atom-script#166]
I was trying to get Script to work but nothing would work. Im running windows 8.1 and i launched from terminal I did everything in the readme but nothing seemed to work.

**Comment by buar** [comment]
For me on Windows 7:

'python' is not recognized as an internal or external command,
operable program or batch file.

Python's directory is in path and runs fine from cmd.

**Comment by buar** [comment]
setx fixed the problem for me, despite already having the python directory in the path environment var.

**Comment by Gernatch** [comment]
This didn't work for me. Even when I type "python" into cmd, it doesn't work. I get the same message. However if I type "py" into cmd. That works. Is atom trying to use "python" instead of "py" when running the code?
