### ISSUE TITLE
Wont compile c++ code (possibly any code)

### ISSUE THREAD

**Issue by GreenFoxx** [rgbkrk/atom-script#1683]
I keep getting this error message when trying to compile and run a c++ source file:

`g++: error: /mnt/c/Users/nano1778/Desktop/Test/test.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
[Finished in 0.164s]`

That directory definitely exists except its C:/Users/nano1778/Desktop/Test/test.cpp in explorer. Help?

**Comment by MaxGraey** [comment]
You have got windows platform so you could try to install [MinGW](http://www.mingw.org/).
