### ISSUE TITLE
Unexpected token, expected { 

### ISSUE THREAD

**Issue by Massimo-code** [rgbkrk/atom-script#1685]
Hello everybody!
I am trying to code with node on Atom, using script package. 

Here is the simple example:

var mysql = require('mysql');

var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'root',  //your root username (leave as root)
  database : 'users',   //the name of your db (create this if you haven't already)
  password : process.env.password   //your root user's password
});

var q = 'SELECT * FROM users';

connection.query(q, function (err, results, fields) ({
  if (err) throw err;
  console.log(results);
});

connection.end();

I saved it but when I ran the code I do receive feedback : 

SyntaxError: C:/Users/.atom/packages/script/node_modules/.bin/babel: Unexpected token, expected { (12:52)
  10 | var q = 'SELECT * FROM users';
  11 | 
> 12 | connection.query(q, function (err, results, fields) ({
     |                                                     ^
  13 |   if (err) throw err;
  14 |   console.log(results);
  15 | });
[Finished in 1.772s]

I did check into previous issues but none of them could help, anyone has idea how to solve that issue?

Thanks for any help!

**Comment by MaxGraey** [comment]
This issue in your code:
```js
connection.query(q, function (err, results, fields) { // <-- remove '('
...
```

**Comment by Massimo-code** [comment]
Thanks a lot, I am blind after hours of coding

cheers!
