### ISSUE TITLE
Can I run python through linux subsystem on windows?

### ISSUE THREAD

**Issue by sliddjur** [rgbkrk/atom-script#1698]
I don't want to clutter my windows machine with more apps, so I am wondering if its possible to use python through WSL. 

If I open cmd.exe or powershell in Windows, I can just run bash -c python3 myfile.py

How can I do the same thing with atom-script?

![image](https://user-images.githubusercontent.com/10002057/44628692-43cac580-a945-11e8-9881-c4b710f8a625.png)

**Comment by DamnedScholar** [comment]
The command should be `bash` and the arguments should probably be `-c "python3 {FILE_ACTIVE}"`. Try it like that.

**Comment by sliddjur** [comment]
yes, getting closer. but now I get this error

```
[Command: bash -c 'python3 {FILE_ACTIVE_NAME}' -u 'C:\Users\Olof Lundgren\Documents\ktbyers_python\week4\dict.py']
python3: can't open file 'dict.py': [Errno 2] No such file or directory
[Finished in 0.241s]```

**Comment by DamnedScholar** [comment]
That's interesting. The replacement doesn't seem to be working. You may have to use a different package, like `process-palette`.

**Comment by sliddjur** [comment]
Not an issue for me anymore.
