### ISSUE TITLE
Cannot run Python code

### ISSUE THREAD

**Issue by prosimplecoding** [rgbkrk/atom-script#1721]
How to fix this problem? Please, help me.

Atom version: 1.31.0
OS: Windows 7

![python-problem](https://user-images.githubusercontent.com/36481166/46157357-f9ff3300-c294-11e8-8145-2780f4d5eece.png)

**Comment by LeGoffLoic** [comment]
That's interesting, I run it with the sane config and it works great. What version of python do you run ?

**Comment by prosimplecoding** [comment]
Python version 3.7.0. I reinstalled python and checked "Add to PATH" setting during installation.
