### ISSUE TITLE
I am unable to run a Powershell script that is in a folder that contains spaces

### ISSUE THREAD

**Issue by ghost** [rgbkrk/atom-script#177]
For instance, the path is `C:\Usher\SourceTree\Powershell Scripts\testing\testing_users.ps1` but I receive the following error when running the script in Atom:

``` powershell
The term 'd:\Usher\SourceTree\Powershell' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try 
again.At line:1 char:1
+ d:\Usher\SourceTree\Powershell Scripts\testing\testing_users.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (d:\Usher\SourceTree\Powershell: 
   String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

When I run the code from Powershell like ".\testing_users.ps1" it works fine

**Comment by zbadrawy** [comment]
I had the same issue. My PC crashed and when I restarted, I would get that message over and over. For some reason the C:\Go\bin path I set in environment variables was gone. Typing it back in fixed it. Check your paths and make sure they're all alright. Hope this helps!
