### ISSUE TITLE
node's command can't find

### ISSUE THREAD

**Issue by mingyu0519** [rgbkrk/atom-script#181]
```
Unable to run
node
Is it on your path?
PATH: /usr/bin:/bin:/usr/sbin:/sbin
execvp(): No such file or directory
```

**Comment by mdeggies** [comment]
@HarrisRobin @erran 
Did you guys ever figure out how to store & save the command path (without having to retype it every time?)

**Comment by rgbkrk** [comment]
Haven't had much time to work on this package other than some small fixes and PR merges. It's open to a contributor to look into.

**Comment by huangjihua** [comment]
Unable to run

babel-node
Did you start Atom from the command line?

  atom .
Is it in your PATH?

PATH: /usr/bin:/bin:/usr/sbin:/sbin

**Comment by huangjihua** [comment]
`Unable to run

babel-node
Did you start Atom from the command line?

  atom .
Is it in your PATH?

PATH: /usr/bin:/bin:/usr/sbin:/sbin`

**Comment by Kimilhee** [comment]
same problem with @huangjihua

**Comment by dengjonathan** [comment]
@huangjihua @Kimilhee Had the same problem- it's because you did not have the babel package installed in node.  I think the updated atom-script uses Babel for ES6 support.

Below is what i did:

`npm install -g babel-cli`

**Comment by ArnoBuschmann** [comment]
Hm, same problem as @huangjihua @Kimilhee, I tried
```npm install -g babel-cli```
but it's not solving the issue. Any suggestions?

**Comment by Maxhodges** [comment]
babel cli docs discourage running globally

```
Note: Since it's generally a bad idea to run Babel globally you may want to uninstall the global copy by running npm uninstall --global babel-cli.
```

**Comment by ProVadimir** [comment]
Hello, i have problem with Atom!
help me, please!
![photo](https://user-images.githubusercontent.com/32485847/31126951-0a58a7a4-a856-11e7-9dee-c9cd1ba0ed58.png)

**Comment by GuidoS** [comment]
I still don't understand the underlying issue that caused this problem and if you should not install babel globally, what is the solution?

**Comment by bmanandhar** [comment]
I am trying to run JavaScript program on 'atom' editor (not using command prompt) but having error : 'Unable to find command: node
Are you sure PATH is configured correctly?'
Where as Python program runs without issue.

Any suggestion, mine is desktop, Windows 7,
thanks
