### ISSUE TITLE
SCRIPT RUNS EVERY PYTHON CODE ON MY MAC OTHER THAN THIS

### ISSUE THREAD

**Issue by YashKarthik** [rgbkrk/atom-script#1914]
help!!!https://github.com/Yash10bloodstorm/__Python__/blob/master/pyth.py 
this package doesn't run this

**Comment by Yash10bloodstorm** [comment]
SyntaxError: Non-ASCII character '\xc6' in file__Python__/trig.py on line 61, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
[Finished in 0.058s] .https://github.com/Yash10bloodstorm/__Python__/blob/master/trig.py

someone check for any errors or whatsoever.
