### ISSUE TITLE
f string syntax error

### ISSUE THREAD

**Issue by chiaolinghong3d** [rgbkrk/atom-script#2255]
Tried to print a simple f string, the console shows "SyntaxError: invalid syntax", but it runs in the Terminal just fine.

**Comment by Kacarott** [comment]
Script by default uses Python 2. Have you switched it? If you haven't, you just need to change a couple commands in /script/lib/grammars/python.coffee from `command: 'python'` to `command: 'python3'`.

**Comment by chiaolinghong3d** [comment]
@Kacarott Thank you so much! This fixed it! :) 

- Chiaoling
