### ISSUE TITLE
Add support for Rust

### ISSUE THREAD

**Issue by Fireforge** [rgbkrk/atom-script#233]
If the file is setup as a project with Cargo, this is easily done by running `cargo run` in the same directory as the `.rs` file.

If Cargo can't be used, either because it's not installed or because there is no `Cargo.toml` in the project, then a single Rust file can be run with the following two commands back-to-back (at least on Windows):

   `rustc helloworld.rs` & `helloworld.exe`

**Comment by rgbkrk** [comment]
Fixed by #260.
