### ISSUE TITLE
Add a configuration option to execute scripts in context of parent directory

### ISSUE THREAD

**Issue by caleb531** [rgbkrk/atom-script#248]
I just stumbled across this package, and I like it very much, as it works very well. However, I've noticed one small annoyance when using it. For what it's worth, I'm not proposing a change to the default behavior, but rather, a configuration option for changing such.

As far as I can tell, I can only execute the given file within the context of the current project directory in Atom (whatever path is showing in the titlebar). I find to be a bit troublesome when I am reading/writing files in any one of my scripts, because—if Atom's current project directory does not match the parent directory of said script—I will receive the typical _file not found_ error from my script's compiler/interpreter.

Therefore, I propose a configuration option to enable (what _I_ believe is) the more intuitive behavior of having a script execute in the context of its parent directory (as opposed to the current project directory). This would be greatly appreciated.

Thanks,
Caleb

**Comment by caleb531** [comment]
Hi, @erran.

I just wanted to let you know that I discovered a simple and straightforward way to ensure correct file paths within my existing Python scripts:

```
os.chdir(os.path.dirname(os.path.realpath(__file__)))
```

I also realize that I should probably be writing future I/O-related scripts in this way, so that the current working directory no longer matters. Therefore, I technically no longer need this option within Atom Script. Unless, of course, you still deem it a worthwhile option, but that's totally up to you. :)

Caleb

**Comment by andrewning** [comment]
This was closed, so I was wondering if a good solution was found?  The default behavior seems to be to use the project directory as the CWD, but I'd like to set CWD to always be the directory of the run file (which is often different).  I know I can manually set a specific path in the run options, but then I'd have to manually set a path for every single file I open and also redo that whenever I reopen atom.  I used a configuration option like this in ST2/3, and the [atom-build](https://atom.io/packages/build) package provides something similar where you can set cwd to a dynamic variable: {FILE_ACTIVE_PATH}.

Anyway, I can work around, just wondering if a solution was found.
