### ISSUE TITLE
Python Console Output not displaying in Atom [Windows 8.1]

### ISSUE THREAD

**Issue by Pome-ro** [rgbkrk/atom-script#259]
I just tested this with powershell and it works as expected, however with python I do not get any output in to script box except for the time the script took to finish. Instead I get a python window that opens and closes as the script starts and finishes. Any idea why this could be happening?

**Comment by Tiago-Moreira** [comment]
Hi,
I'm having the same problem but even when a run as an administrator it doesn show the final output in windows power shell.

here it is:

a = input('digite um valor: ')
b = input('digite outro valor:')
soma = float(a + b)
print('soma')

It asks for the inputs and shows it but doesnt show the output.

Can you help me?
