### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jpietrangelo** [rgbkrk/atom-script#269]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
ScriptOptionsView.close (/Users/jmp/.atom/packages/script/lib/script-options-view.coffee:71:9)
```

**Comment by erran** [comment]
See #266. I'll take a look at refactoring this. Thanks for reporting this.
