### ISSUE TITLE
Pass to log

### ISSUE THREAD

**Issue by tokejepsen** [rgbkrk/atom-script#270]
It there a way to pass logs to the log window from outside the package?

Would like to support this package and use the log window for other packages.

**Comment by rgbkrk** [comment]
What kind of packages? There aren't any exposed ways of doing this right now (we don't consume any events), but I'd probably want to understand what you're thinking of.

**Comment by tokejepsen** [comment]
There are some packages like;

https://github.com/davidpaulrosser/atom-maya
https://github.com/tokejepsen/atom-modo
https://github.com/tokejepsen/atom-nuke

They pass a script onto the hosts (Maya, Modo, Nuke) through commandport. The problem is that the developer console gets very cluttered, so it would be nice to have a log like this package. So I'm looking to pass on results to this package's log.

Or maybe there is another way of working?

**Comment by tokejepsen** [comment]
Found this a package for this, so closing this issue:)

https://github.com/tcarlsen/atom-message-panel
