### ISSUE TITLE
Uncaught BufferedProcessError for files not shown on PATH

### ISSUE THREAD

**Issue by pauldhawk** [rgbkrk/atom-script#275]
When I try to run Script using the `scala` grammar the following error error is thrown:
```
/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:104 Uncaught BufferedProcessError: Failed to spawn command `scala`. Make sure `scala` is installed and on your PATH
```
`scala` is in my path. its located at `/usr/local/bin/scala`  `/usr/local/bin/` is in my etc/paths file.

**Comment by erran** [comment]
@hawkerchuck the deprecations are solved by https://github.com/rgbkrk/atom-script/pull/278 which is in testing.

**Comment by erran** [comment]
I'm able to reproduce this with a command I don't have installed locally: ![screen shot 2015-01-31 at 20 42 50](https://cloud.githubusercontent.com/assets/1694055/5990804/dd9dc2c6-a989-11e4-8f35-b45406107499.png)

@hawkerchuck did you start Atom from the command line or via the Desktop/Dock icon? See if [these steps](https://github.com/rgbkrk/atom-script/issues/61#issuecomment-37337827) allows your installation of Atom to find script.

**Comment by caleb531** [comment]
If I may pitch in, the simplest solution that has solved the majority of issues (for me, at least) is to add the following line to Atom's Init Script (`init.coffee`):

```coffeescript
process.env.PATH = ['/usr/local/bin', process.env.PATH].join(':')
```

After reloading Atom (either through the command palette or by simply restarting Atom), Atom Script should recognize any packages within `/usr/local/bin`.

**Comment by erran** [comment]
@pauldhawk I've opened a PR to fi the uncaught error. The BufferedProcess API was changed without being deprecated underneath our feet. In terms of `scala` not being detected on your path that should be solvable my ensuring atom starts with `scala` in `process.env.PATH`. @caleb531's suggestion and the link above should get you up and running there.

**Comment by pauldhawk** [comment]
i got it working. sorry i forgto to close the tx. thanks

paul

-- Paul Hawk

**Comment by erran** [comment]
@pauldhawk Good to hear thanks!
