### ISSUE TITLE
Using Julia 

### ISSUE THREAD

**Issue by aeroflux** [rgbkrk/atom-script#281]
Hello,
At the moment I am coding a couple of functions in Atom and then keep jumping to Julia's command line in order to run it. Now I wanted to use the Script package, I have selected the correct Julia grammar but, running the script only yields the time it took to complete the calculation without answer. Example:

```
a=2
b=1
c=a+b
println(c)
```

Script box shows:
```
[Finished in 4.357s]
```

**Comment by aeroflux** [comment]
Its working fine.

**Comment by Dario-Rosa85** [comment]
I have exactly the same problem: how the problem has been fixed?
