### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Equilibri0** [rgbkrk/atom-script#282]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
ScriptView.initialize (/Users/equilibri0/.atom/packages/script/lib/script-view.coffee:29:9)
```

**Comment by erran** [comment]
This is a duplicate of #266. See https://github.com/rgbkrk/atom-script/pull/278 which is waiting to be tested by a second contributor before merging and pushing.
