### ISSUE TITLE
Add LineNumber Based support for Julia

### ISSUE THREAD

**Issue by bisraelsen** [rgbkrk/atom-script#284]
I believe this should be possible as I have used it in LightTable and Julia has an interactive terminal.

I don't think this has been posted already, I took some time to check.

**Comment by erran** [comment]
@bisraelsen Thanks for taking the time to check existing issues. Currently Selection Based and File Based Julia runs are supported. Is it possible to run Julia by specifying the line number (you should be able to use the selection based runner to run a specific line today). Line number based builds are generally used for testing related tools.

**Comment by rgbkrk** [comment]
How does LightTable do it? Are we talking full session support with a REPL over time?
