### ISSUE TITLE
Add LineNumber Based support for ShellScript

### ISSUE THREAD

**Issue by starquake** [rgbkrk/atom-script#293]
Would make it more useful when using a file with a bunch of frequently used shell commands

**Comment by erran** [comment]
Currently File Based and Selection Based execution are supported. Selection based execution will allow you to select one or more lines while line number based execution will execute code based on the current line number. If you really do want the latter how would you go about executing a shell script by line number?

**Comment by starquake** [comment]
I was thinking of something like this: 

Contenst of dev-commands.sh:
```bash
exit

# Run cordova in browser
cordova run browser

# Build app for iOS
cordova build ios

# Build app for Android
cordova build ios

# Start android emulation
cordova emulate android
```

Then put the cursor on a particular line and hit the line number based execution keyboard shortcut.

**Comment by erran** [comment]
@starquake Sorry, never noticed your response. It seems like selecting the line (and using `Script: Run`) would just be one more step in your proposed workflow.
