### ISSUE TITLE
print statements not always flushed to stdout

### ISSUE THREAD

**Issue by onlinespending** [rgbkrk/atom-script#302]
In Python if I have something like the following, it works fine when run with Script

```python
  for x in range(0,20):
    print '.'
    sys.stdout.flush()
    time.sleep(1)
```

But if I change the code to eliminate the newline that's printed with each print statement by either of the following two methods (one with comma at end of the print statement, another using sys.stdout.write), the output is not flushed to stdout when using Script, despite the sys.stdout.flush() call. However, if I run the python interpreter from the command line (outside of Atom) it works just fine.

```python
  for x in range(0,20):
    print '.',
    sys.stdout.flush()
    time.sleep(1)
```

```python
  for x in range(0,20):
    sys.stdout.write('.')
    sys.stdout.flush()
    time.sleep(1)
```

Can someone verify this bug/limitation? Is there a workaround?

**Comment by erran** [comment]
@onlinespending Mostly a limitation of how we execute the command. We use Atom's BufferedProcess to execute commands. See also https://github.com/rgbkrk/atom-script/issues/226 where there is a lot of discussion on this already.
