### ISSUE TITLE
Python 3 instead of Python 2 [Mac O$]

### ISSUE THREAD

**Issue by projetmbc** [rgbkrk/atom-script#313]
Hello.

I would like to launch **all** my Python scripts with the 3 version instead of 2 version. I can't uninstall the 2 version because it is used by my OS.

Is there an easy way to do that ?

**Comment by rgbkrk** [comment]
Atom uses whatever is on your PATH as the default Python. Make sure you launch atom from the terminal:

```
$ atom
```

**Comment by erran** [comment]
In addition you can use the Run with Options or a shebang line to update the version used.

**Comment by projetmbc** [comment]
I will use the shebang. Thanks.

**Comment by erran** [comment]
:+1:
