### ISSUE TITLE
Can't import modules installed from pip

### ISSUE THREAD

**Issue by jalavosus** [rgbkrk/atom-script#314]
Hey, 
when I try to run script on a python file, if I have any imports that aren't part of Python's standard lib, then I get an ImportError stating that the module I'm trying to import doesn't exist. Is there any way to get script to read my pythonpath? I'm using python installed via <code>brew install</code> on OS X, not the Apple standard.

**Comment by jalavosus** [comment]
Please close this -- I figured out I had /usr/bin/python in my file instead of /usr/local/bin/python.

**Comment by The-Penultimate-Defenestrator** [comment]
Any solution if I don't want to change my script? Any way to make this default behavior?
