### ISSUE TITLE
Freezing on python input

### ISSUE THREAD

**Issue by pauloruberto** [rgbkrk/atom-script#328]
When trying to run something needing an input, the entire shell freezes up.

ex.

```python
c = input('Enter your favourite number: ')
```

**Comment by erran** [comment]
@pauloruberto Currently STDIN is not supported by the script package. See the ["REPL/STDIN request"](https://github.com/rgbkrk/atom-script/issues?q=is%3Aopen+is%3Aissue+label%3A%22REPL%2FSTDIN+request%22) label.

**Comment by erran** [comment]
@pauloruberto That's not to say that the maintainers and myself wouldn't be interested in helping with a PR adding this functionality. We just seem to be a bit busy for that large of a refactor.
