### ISSUE TITLE
Add Line Number Based support for PHP

### ISSUE THREAD

**Issue by paravatee** [rgbkrk/atom-script#336]
##### Platform: `win32`
---

I have 1 script name's hello.php 

```
<?php
echo "hello world";
?>
```

why I press "shift-ctrl-b" + "shift-ctrl-j" on this file. and then show error :100: 

Line Number Based runner not available for PHP.

If it should exist, add an issue on GitHub, or send your own pull request.

how to fixed this?????????????????????

**Comment by erran** [comment]
@paravatee "Line Number Based" execution will execute the program by file name and line number. PHP doesn't support this. If you want to run a specific line of code you can use the `Script: Run` command after highlighting that line.
