### ISSUE TITLE
Add Selection Based support for R

### ISSUE THREAD

**Issue by Huaraz2** [rgbkrk/atom-script#341]
##### Platform: `linux`
---
I use R a lot and script is a great tool but you are unable to run certain lines of R code, you have to run every single line when you want to check the code which can take a while.

**Comment by erran** [comment]
@Huaraz2 what command would you run to execute a selection of code?

**Comment by Martin-Jung** [comment]
I second that request for better R-support, although I can't figure out a way to pass only a selection to R.
However it seems possible to run the interpreter in a quiet slave mode `R --quiet --slave $file` to pass selections. 
Example can be seen in this sublime 2 plugin:
<http://codereview.stackexchange.com/questions/78181/sublime-text-2-r-build-system-source-file-send-selection-to-interactive-sessio>

**Comment by rgbkrk** [comment]
I think we'd see better R support when we can have actual sessions. I'm toying with using the kernels (including R) from the Jupyter project to do live interaction + plots. Should be a little while though.

**Comment by Huaraz2** [comment]
@erran not quite sure what you mean, I currently use script if I want to check a small bit of R code I have written in atom but if II am writing a lot of R, then I will also use the terminal as I am able to run just the part I want then
