### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated. (script-view.coffee:16:9)

### ISSUE THREAD

**Issue by Kantrael** [rgbkrk/atom-script#357]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Artem\AppData\Local\atom\app-0.188.0\resources\app\src\atom.js:54:11)
HeaderView.close (C:\Users\Artem\.atom\packages\script\lib\header-view.coffee:16:9)
```

**Comment by erran** [comment]
Fixed by #407, new release pending.
