### ISSUE TITLE
Add support for Java plz!

### ISSUE THREAD

**Issue by fr4j4** [rgbkrk/atom-script#359]
plz add support for java

**Comment by erran** [comment]
@fr4j4 How would you execute a Java file?

**Comment by willbaker602** [comment]
For example executing:

public class HelloWorld {
     public static void main(String[] args) {
          System.out.println("Hello world!");
     }
}

Script would probably have to deal with the Java hierarchy of .class and .java files though.

**Comment by linjer** [comment]
Script could probably have limited support, which is where Script is most useful anyway. And what I mean is just small self contained java files people use as scratch/sandboxes. I assume you can link standard libraries and take others in a classpath argument, and assume if they try to run a file with script, it has a the main they want to execute.

Anything more, someone should be using a full focused IDE.

**Comment by rgbkrk** [comment]
#441 added this! Kick it around and let @pardom know what you think.

**Comment by EntilZha** [comment]
Closing since it appears to be implemented by #441
