### ISSUE TITLE
STDIN should be handled

### ISSUE THREAD

**Issue by AnDroidEL** [rgbkrk/atom-script#385]
When I use the command *input* (on Python) and *readline* (on PHP) and I execute the script, just the commands that enter with the data don't work. Example:

### Python 3 - Example
```python
print ("Testing a print") # It works
msg = input("Write a message: ") # It does not works
```
### PHP 5 - Example
```php
<?php

$msg = readline("Write a message: "); // It does not works
echo $msg;

?>
```
Probably, others programming languages have this same problem.

**Comment by rgbkrk** [comment]
Yeah, we don't currently handle STDIN.

**Comment by AnDroidEL** [comment]
So, how to I do for it works on my script?

**Comment by rgbkrk** [comment]
We'd need someone to implement handling input on atom-script itself.

We're still using Atom's `BufferedProcess` module, so I assume we'd have to perform some tricks to work between that and input from users. The better route might be to set up a pseudo terminal in the little display widget as all it does right now is spit out output. I'm sorry it doesn't do more, there's just not focused effort to address that right now.

**Comment by AnDroidEL** [comment]
I understand. Still, thanks for the support and for the information! :)

**Comment by Jamesernator** [comment]
In the meantime a functional solution is just to have a data file containing intended stdin input and a testing shell script eg:
```bash
python3 test_script.py < data_file_with_stdin
```
Useful if you're not trying to test anything particularly interactive.
