### ISSUE TITLE
Run Selection for LUA doesn't work

### ISSUE THREAD

**Issue by ThiconZ** [rgbkrk/atom-script#394]
When trying to run selected text for LUA it only says "[Finished in 0.062s]" but doesn't display any actual code execution. To get code execution to display I have to run the entire file.

**Comment by erran** [comment]
Hi @ThiconZ a few questions:

1. Can you provide a sample script? [Lua's grammar definition](https://github.com/rgbkrk/atom-script/blob/77b1dd40ba/lib/grammars.coffee#L166-L172)
2. What version of Lua are you running?
3. Can you test running the script from your terminal using `lua -e "YOUR CODE HERE"`?

Using the following version allows me to select and see the output of `print("hello world")` in Atom Script:
```
aus-mac-1033 @ ~/g/e/atom-script (master) 🐟  lua -v
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
```

**Comment by ThiconZ** [comment]
@erran I've tested with multiple examples but a simple one is:

https://www.dropbox.com/s/67h7d7wlrhl9ins/lua_sample.lua?dl=0

attempting to select and run lines 3 and 4 results in the issue above.

I'm running Lua 5.1.4 as that's what I'm developing for so I cannot upgrade it to 5.2.x or 5.3.x

When running from command prompt it works perfectly fine.

**Comment by erran** [comment]
@ThiconZ wow, that one should definitely work. I don't have an older version of Lua installed at the moment but I'd imagine the same behavior.

![atom-script-lua-usage](https://cloud.githubusercontent.com/assets/1694055/7442513/3beab9f0-f0da-11e4-998b-fd1e61fdef1b.gif)

**Comment by ThiconZ** [comment]
Yeah I don't know why it doesn't work for me or any other workstation I try it on @erran . I've attempt it only on Windows workstations though so I'm not sure if that could maybe be the issue?
![image](https://cloud.githubusercontent.com/assets/6924950/7442525/49fed716-f0e3-11e4-984e-8b243c918116.png)

**Comment by erran** [comment]
@ThiconZ On the command line how do you pass options to Lua in Windows?

**Comment by ThiconZ** [comment]
@erran the same as Mac and Linux, lua -e

**Comment by erran** [comment]
@ThiconZ What happens if you supply new lines between that?
* If using `\n` line endings: `lua -e 'print("2")\nprint("3")'`
* If using `\r\n` line endings: `lua -e 'print("2")\r\nprint("3")'`

**Comment by ThiconZ** [comment]
@erran you can't explicitly use \n or \r\n when doing -e if you want to simulate another line.

**Comment by erran** [comment]
@ThiconZ I don't understand. If that's the case it may be the issue though since script does exactly that. The selections "code" will be new line separated.

Should they be joined by empty string?

**Comment by erran** [comment]
@ThiconZ I see now.

```
aus-mac-1033 @ ~/g/e/atom-script (master) 🍣  lua -e "print('hello world')\nprint('hello erran')"
lua: (command line):1: unexpected symbol near '\'
aus-mac-1033 @ ~/g/e/atom-script (master) 🍣  lua -e "print('hello world')" "print('hello erran')"
hello world
lua: cannot open print('hello erran'): No such file or directory
aus-mac-1033 @ ~/g/e/atom-script (master) 🍣  lua -e "print('hello world')" -e "print('hello erran')"
hello world
hello erran
```

**Comment by ThiconZ** [comment]
@erran if you copy and paste multiple lines they just get put right next to each other, for example if I try to do a \n like you said it would look like the following, and copy pasting lines 4,5, and 6 look like this as well.
![image](https://cloud.githubusercontent.com/assets/6924950/7442622/7285126a-f0e6-11e4-84f8-dfe4a2e7c523.png)

**Comment by erran** [comment]
Can you modify grammars.coffee in your script package directory? If you go to the package page you should see an "view code" button.

```diff
diff --git a/lib/grammars.coffee b/lib/grammars.coffee
index 4623bba..3efee95 100644
--- a/lib/grammars.coffee
+++ b/lib/grammars.coffee
@@ -166,7 +166,9 @@ module.exports =
   Lua:
     "Selection Based":
       command: "lua"
-      args: (context)  -> ['-e', context.getCode()]
+      args: (context) ->
+        code = context.getCode()
+        ['-e', code?.replace(/[\r\n]+/g, '')]
     "File Based":
       command: "lua"
       args: (context) -> [context.filepath]
```

**Comment by ThiconZ** [comment]
@erran I changed it to that and it seems to work. I'm going to test with a few different things to see if it works properly or if the multiple -e's cause issues with how it scopes things. So far though it seems like it works correctly though so thank you very much.

**Comment by erran** [comment]
> @erran I changed it to that and it seems to work. I'm going to test with a few different things to see if it works properly or if the multiple -e's cause issues with how it scopes things. So far though it seems like it works correctly though so thank you very much.

This doesn't add multiple `-e`s. :wink: This performs it using the syntax you provided by replacing all newlines with empty string. If this works please report back so we can submit it as an update.

**Comment by ThiconZ** [comment]
@erran ah, didn't read through it, just assumed you made it like your last test by adding -e's where a newline would be.

**Comment by ThiconZ** [comment]
@erran alright just did a test case and it did not work with the following error:
lua: (command line):1: '=' expected near '<eof>'
however it does run properly when tested with the online lua demo from: http://www.lua.org/cgi-bin/demo

i'll post the code sample i tested with:

```
Location = {
	["Addons/FPS_Counter"] = {
		XmlRun = {
			["loadGameUI"] = {
				[1] = {file = "FPS_Counter.xml", object = "Panel_FPS_Counter", UIGroup = "PAGameUIGroup_MainUI"}
			},
		},
		LuaRun = {
			["loadGameUI"] = {
				[1] = "FPS_Counter.lua"
			},
		}
	}
}

for addons, tbl in pairs(Location) do
    local fullPath = addons.."/"
    print("fullPath = "..fullPath)
    local style = "loadGameUI"
    print("style = "..style)
    if tbl.XmlRun ~= nil then
        for idx, idxTable in pairs(tbl.XmlRun[style]) do
            print("fullPath = "..fullPath.." idxTable.file = "..idxTable.file.." idxTable.object = "..idxTable.object.." idxTable.UIGroup = "..idxTable.UIGroup)
        end
    end
    if tbl.LuaRun ~= nil then
        for idx, idxFile in pairs(tbl.LuaRun[style]) do
            print("fullpath = "..fullPath.." idxFile = "..idxFile)
        end
    end
end
```

**Comment by erran** [comment]
@ThiconZ while the error I got running that script locally was different I was able to fix the `eof` error I got locally.

```diff
diff --git a/lib/grammars.coffee b/lib/grammars.coffee
index 4623bba..195557f 100644
--- a/lib/grammars.coffee
+++ b/lib/grammars.coffee
@@ -166,7 +166,9 @@ module.exports =
   Lua:
     "Selection Based":
       command: "lua"
-      args: (context)  -> ['-e', context.getCode()]
+      args: (context) ->
+        code = context.getCode()
+        ['-e', code?.replace(/[\r\n]+/g, ' ').replace(/\s+/g, ' ')]
     "File Based":
       command: "lua"
       args: (context) -> [context.filepath]
diff --git a/lib/script-view.coffee b/lib/script-view.coffee
index 69f2349..b7b2252 100644
--- a/lib/script-view.coffee
+++ b/lib/script-view.coffee
@@ -254,6 +254,7 @@ class ScriptView extends View
       console.log "Exited with #{returnCode}"
 
     # Run process
+    console.log("Executed: '#{command} #{args}'")
     @bufferedProcess = new BufferedProcess({
       command, args, options, stdout, stderr, exit
     })
```

**Comment by ThiconZ** [comment]
@erran I still receive the same error, using the following code (added in different types of comments all over it, a bit different from the second one posted above)

```lua
Location = {
	["Addons/FPS_Counter"] = {
		XmlRun = {
			["loadGameUI"] = {
				[1] = {file = "FPS_Counter.xml", object = "Panel_FPS_Counter", UIGroup = "PAGameUIGroup_MainUI"}
			},
		},
		LuaRun = {
			["loadGameUI"] = {
				[1] = "FPS_Counter.lua"
			},
		}
	}
}

for addons, tbl in pairs(Location) do
    local fullPath = addons.."/"
    print("fullPath = "..fullPath)
    local style = "loadGameUI"
    print("style = "..style)
    if tbl.XmlRun ~= nil then
        for idx, idxTable in pairs(tbl.XmlRun[style]) do
            print("fullPath = "..fullPath.." idxTable.file = "..idxTable.file.." idxTable.object = "..idxTable.object.." idxTable.UIGroup = "..idxTable.UIGroup)
        	--[[
			different ending for multiline comment
			print("should not see this line")
			print("or this one")--]]
		end
    end
	-- comment on seperate line
    if tbl.LuaRun ~= nil then --comment on code line
        for idx, idxFile in pairs(tbl.LuaRun[style]) do--comment against code without space
            print("fullpath = "..fullPath.." idxFile = "..idxFile)
			--[[ multiline comment
			print("fullpath = "..fullPath.." idxFile = "..idxFile)
			]]
        end
    end
end
```

**Comment by erran** [comment]
@ThiconZ I can see that being an issue. I'm not sure how to work around it.

**Comment by ThiconZ** [comment]
@erran i'm not sure how possible/reasonable this is, but since running the entire file works perfect would this be a possible 'fix'/workaround: when running selected text, create a new temporary file that contains all of the selected text only, and run that as a full file, then once execution of it has completed it is deleted.

**Comment by ThiconZ** [comment]
Alright @erran so I just implemented my idea from above and it works, but it could probably be changed a bit so it doesn't interfere possibly with other things. Currently it deletes the existing temp files, creates a temp file with the selected text, then calls lua using that path so it can run just fine without any issues caused by including comments or anything. Still want to get the number of lines above the selected text and add in blank lines for each one of those so that if the selected text does error that the error line numbers match up with the source text.

Here is how I currently have the grammar part for Lua looking
```
Lua:
    "Selection Based":
      command: "lua"
      args: (context) ->
          GrammarUtils.deleteTempFiles()
          code = context.getCode()
          tmpFile = GrammarUtils.createTempFileWithCode(code)
          [tmpFile]
    "File Based":
      command: "lua"
      args: (context) -> [context.filepath]
```

**Comment by erran** [comment]
@ThiconZ Awesome! I completely forgot about the temp file utility methods. Funny that you were looking for the ability to prepend lines check out https://github.com/rgbkrk/atom-script/blob/master/lib/code-context.coffee#L32-43

**Comment by ThiconZ** [comment]
@erran I made it prepend blank lines based on number of lines above the selected text in the source file now, so error line numbers will match up properly with the source file view. Below is the code used, it could still be cleaned up and the deleteTempFiles should probably get moved to somewhere else such as being called only when script execution is complete. This also only uses \n so \r support would still need to be added in if this were to make it into the next official commit
```
Lua:
    "Selection Based":
      command: "lua"
      args: (context) ->
        GrammarUtils.deleteTempFiles()

        editor = atom.workspace.getActiveTextEditor()
        editorLines = editor.getText().split("\n")
        selectionLines = editor.getSelectedText().split("\n")
        cursorLineNumber = editor.getCursor().getScreenRow()
        prependCount = 0

        if editorLines[cursorLineNumber] is selectionLines[0] then prependCount = cursorLineNumber
        else if editorLines[cursorLineNumber - 1] is selectionLines[0] then prependCount = cursorLineNumber - 1
        else if editorLines[cursorLineNumber] is selectionLines[selectionLines.length - 1] then prependCount = cursorLineNumber - (selectionLines.length - 1)
        else if editorLines[cursorLineNumber - 1] is selectionLines[selectionLines.length - 1] then prependCount = cursorLineNumber - (selectionLines.length - 1)

        code = ''
        i = 0
        while i < prependCount
            code += '\n'
            i++

        code += context.getCode()
        tmpFile = GrammarUtils.createTempFileWithCode(code)
        [tmpFile]

    "File Based":
      command: "lua"
      args: (context) -> [context.filepath]
```

**Comment by erran** [comment]
If `\n` works on your Windows machine I wouldn't say it was necessary. I was assuming your files had `\r\n` line endings. Please see my comment though, I think your prepend logic is similar to the option you can pass into the `getCode` method.

**Comment by ThiconZ** [comment]
Just took a look at it @erran and it seems it does do pretty much what my code above did, but faster and better. Switched the code over to use it, so seems this is pretty much ready to be in the next commit. Just might want to move around that deleteTempFiles() method as stated above.
```
  Lua:
    "Selection Based":
      command: "lua"
      args: (context) ->
        GrammarUtils.deleteTempFiles()
        code = context.getCode(true)
        tmpFile = GrammarUtils.createTempFileWithCode(code)
        [tmpFile]

    "File Based":
      command: "lua"
      args: (context) -> [context.filepath]
```

**Comment by erran** [comment]
@ThiconZ `deleteTempFiles` is automatically called when atom-script is deactivated. You can just remove that call. Could you create a pull request with your changes? @rgbkrk or I will review it and test it. Thanks for giving ally he feedback here! :+1:

**Comment by ThiconZ** [comment]
@erran alright I created the pull request for it now.

**Comment by ThiconZ** [comment]
@erran I fixed the white spacing now, so it should be just fine to merge hopefully at this point. Also because of how this works I'd imagine you could use this for other languages in place of how they currently do selection base running and even give other languages that don't currently have selection based running, it as well.

**Comment by erran** [comment]
@ThiconZ Definitely possible. The changes in this pull request combine some logic we use for selection based Python and PHP. In my opinion we should enable them on a per language basis though.
