### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by tangshi** [rgbkrk/atom-script#413]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:57:13)
Object.activate (/Users/tangshi/.atom/packages/script/lib/script.coffee:30:9)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30)
```

**Comment by erran** [comment]
This is a duplicate. Please see #407 which resolves it.
