### ISSUE TITLE
can not import home-made python package

### ISSUE THREAD

**Issue by jingpengwu** [rgbkrk/atom-script#424]
my own package was saved in /home/libs/

I have the following lines in .bashrc
export PYTHONPATH=$PYTHONPATH:"/usr/people/jingpeng/libs"

I can import my package using ipython in terminal and spyder. I usually use spyder to edit my script. I'd like to migrate to atom. But this is a big problem for me.

**Comment by rgbkrk** [comment]
Make sure to [run `atom` from the command line](https://github.com/rgbkrk/atom-script#atom-cant-find-node--ruby--python--my-socks) so it picks up your existing environment variables.

**Comment by jingpengwu** [comment]
thanks, it works!
