### ISSUE TITLE
Select Python version

### ISSUE THREAD

**Issue by Lijantropique** [rgbkrk/atom-script#427]
Hello,
Is it possible to select the Python version to run a specific script/module?
I work with both Python 2.7 and 3.4 and by default Script always uses 3.4.

Thanks a lot.

**Comment by rgbkrk** [comment]
script uses whatever is on your `$PATH` when it boots (or windows path).

There are two ways to pick the executable, with "run options" (cmd-shift-i on Mac) or by setting the shebang line at the top (e.g. `#!/usr/bin/env python2`)

**Comment by Lijantropique** [comment]
Thanks a lot, didn't know about the run options in Script.

**Comment by rgbkrk** [comment]
No prob, thanks for reaching out!
