### ISSUE TITLE
Info that shows info after running script appears twice.

### ISSUE THREAD

**Issue by JustCameron** [rgbkrk/atom-script#440]
I tried in an html document, which I knew wasn't support, a javascript and a blank document. All three produced the same result - two dialogues. Also, when you close one dialogue, the other closes with it.

I updated to Script 2.22.0 not too long ago and this started to happen. Beforehand, only one instance of the info appeared.

HTML document:
![htmldoc](http://puu.sh/hIkTW/da54c09960.png)

JavaScript document:
![jsdoc](http://puu.sh/hIkRb/5a043394d9.png)

Blank document:
![Image](http://puu.sh/hIkJI/90a10a4362.png)

* Windows 7
* Atom 0.196.0
* Script 2.22.0

**Comment by rodrigomb81** [comment]
In my experience this only happens when running something after updating script  *without* "restarting" atom. If you close atom, open it again and try to run something, everything should work as expected.

**Comment by JustCameron** [comment]
Just did that now and it's fixed itself... Now don't I feel stupid. Thanks, and sorry for my inablility to think about actually closing and reopening.

**Comment by rgbkrk** [comment]
> Thanks, and sorry 

No problem, thanks for filing an issue with details. The first time I ran into that I was super confused.
