### ISSUE TITLE
Unable to run node

### ISSUE THREAD

**Issue by willbaker602** [rgbkrk/atom-script#445]
I installed Script via Terminal with "apm install script". I then launched Atom via Terminal with "atom". When I try to run a Javascript file, it simply gives me the following error:
  " Unable to run
    node
    Is it on your path?
    PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin "
I read the readme multiple times and went through the workaround solutions. I also made sure to launch Atom from the Terminal with the command "atom". I can't seem to find anything that works. I am running Atom on OS X 10.10.3 using Atom 0.198.0 and Script 2.23.0. Any ideas on how I can get Script to run correctly? Thanks!! Any help is much appreciated.

**Comment by rgbkrk** [comment]
Only thing I can think of is making sure to fully quit Atom (command-q it!) then try to open from the terminal. I'm assuming you can run node on the terminal currently with `node`?

**Comment by willbaker602** [comment]
@rgbkrk I am a complete noob when it comes to programming on a Mac! Do I need to install node.js somewhere or something similar? I assumed between Atom, Atom-Script, and Safari natively supporting Javascript I wouldn't need to install other libraries (as opposed to Java for example).

**Comment by rgbkrk** [comment]
Ah, yes. You'll need to [install node](https://nodejs.org/download/) or [iojs](https://iojs.org/en/index.html). Atom script uses the node available to you rather than trying to use Atom's built in version (which is actually iojs). Best of luck!

One suggestion, if I may: use [homebrew](http://brew.sh/) on your Mac to install packages.

**Comment by willbaker602** [comment]
@rgbkrk Thank you thank you! Totally fixed my problem. You're the best!

**Comment by antonmladenov** [comment]
Hi all,

I still get the same error. 

What I've done so far is the following:
- installed Script
- installed node and apm
- installed Shell Commands
- open Atom from the Terminal (open -a atom, right?)
- check the $PATH (/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin, right?)

I am reading for 3 days in a row and also checked many forums and blogs.

Am I missing anything? What that would be? 
Any ideas?

Cheers!

**Comment by lincolnfrias** [comment]
In my case (Linux, Ubuntu), the solution was to install node-legacy besides nodejs. I just did:
`sudo apt install  node-legacy`
