### ISSUE TITLE
Setting to disable 'run by selection'

### ISSUE THREAD

**Issue by caleb531** [rgbkrk/atom-script#459]
Hi,

In short, I'd love a setting that disables the running of selected code (and in such a case, would always run the contents of the entire file, as usual).

I desire such a setting simply because I've never intentionally used the 'Run by Selection' feature. In fact, I've found it more bothersome than helpful (_e.g._ when I have text selected by coincidence but I still desire to run the script in its entirety).

**Comment by TheIdealis** [comment]
Hi @caleb531 
you can set this feature in the settings (Ignore selection). Alternatively, you can add
```cson
  script:
    ignoreSelection: true
```
in your `config.cson`

**Comment by caleb531** [comment]
Excellent, thanks very much @TheIdealis. That should work perfectly.
