### ISSUE TITLE
Run special commands, like pdflatex

### ISSUE THREAD

**Issue by JPFrancoia** [rgbkrk/atom-script#460]
Hi !

First of all, I'm new to Atom. I'm trying to move from Vim.

Over the years with Vim, I set up a very smooth workflow. Especially for Latex. I use a particular command to compile my .tex files:

```
exe '!pdflatex -output-directory ./output/ '.e.'.tex; bibtex ./output/'.e.'.aux; pdflatex -output-directory ./output/ '.e.'.tex; pdflatex -output-directory ./output/ '.e.'.tex; mv ./output/'.e.'.pdf ./'
```

It basically run pdflatex several times, put the output files in a special directory, etc.

I don't exactly know how atom-script work, but I assume somewhere in the code, with a type file goes a command to run. ex:

.py -> python $the_file_name

Am I right ?

So, I wonder if I can add/modify the code to add my special command for Latex.

**Comment by rgbkrk** [comment]
You could add LaTeX as a grammar (see https://github.com/rgbkrk/atom-script/blob/master/lib/grammars.coffee), but that'd just be weird. Seems more like you'd want this to be part of some build package.

**Comment by rififi** [comment]
Yeah I know, but I could keep the same shortcut than any other language to build my .tex file.

For example, to run a python script, I press F5.
To compile a tex file, I press F5.

**Comment by rififi** [comment]
Ok, I'm trying to implement Latex in the grammar. I started simply:

```
  Latex:
    "File Based":
      command: "touch"
      args: (context) -> [context.filepath]
```

But of course, when I try to use it on a tex file, I get the error:

```
Command not configured for LaTeX!
```

I think I have to assign this command to a Tex file type somewhere, don't I ?

**Comment by erran** [comment]
The key for the grammar is case-sensitive. :) Use "LaTex" as the key for
that entry.

On Tue, Jun 9, 2015 at 10:55 AM, rififi <notifications@github.com> wrote:

> Ok, I'm trying to implement Latex in the grammar. I started simply:
>
>   Latex:
>     "File Based":
>       command: "touch"
>       args: (context) -> [context.filepath]
>
> But of course, when I try to use it on a tex file, I get the error:
>
> Command not configured for LaTeX!
>
> I think I have to assign this command to a Tex file type somewhere, don't
> I ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rgbkrk/atom-script/issues/460#issuecomment-110298511>.
>



-- 
Sincerely, Erran Carey

Email: me@errancarey.com
Twitter: @errancarey
Website: http://erran.me

**Comment by MrAdam** [comment]
LaTeX has been added to the package, using "latexmk" command which should work for most people.
