### ISSUE TITLE
Updating won't ever finish

### ISSUE THREAD

**Issue by batjko** [rgbkrk/atom-script#476]
Hi there,

Whenever there is a new version out, and I click the Update button, it _seems_ to never actually finish, and the button stays on "Updating..."
![image](https://cloud.githubusercontent.com/assets/7287076/8392414/450f541c-1ce2-11e5-88ff-26d809902e59.png)

When I reload Atom, I see the update actually has done it's job, i.e. the new version is there and works. It's just that the Update button on the Settings View doesn't seem to have gotten the memo.

Now, I figured at first it might be a bug on Atom's Settings View, but then I noticed that this only ever happens with this one package.
All other community packages I have (several dozens) finish just fine on their own.

**Comment by rgbkrk** [comment]
That's so weird. Not really sure how this happens or where we get triggered. As far as I know, we don't do anything fancy on install - just present ourselves as a typical package.

**Comment by batjko** [comment]
It could still be a Settings Updater issue of some sort, it's just weird that it has happened only ever with this package for the last few patches and minor versions.

**Comment by dessant** [comment]
I've been using atom-script since Atom 1.0, but I've seen it successfully update maybe twice. Usually a restart is needed, until then the update hangs and the plugin does not work.

I have not experienced this issue with other plugins.

**Comment by nixel2007** [comment]
@dessant It was fixed in last release. Next updates will end successfuly

**Comment by dessant** [comment]
@nixel2007 you mean 3.6.3? The issue was still there as I updated to the last version earlier today.

Please reopen.

**Comment by nixel2007** [comment]
@dessant this issue was solved IN 3.6.3. Next releases will work correctly

**Comment by dessant** [comment]
Ah, because during the last update Atom was still trying to deactivate a buggy script version, ok, it is clear now. :wink:

**Comment by dessant** [comment]
The same was the case while updating from 3.6.3 to 3.7.0.

**Comment by nixel2007** [comment]
@dessant could you provide any logs from console (ctrl-alt-i)? if there any

**Comment by dessant** [comment]
There were no errors or anything, maybe it is https://github.com/atom/settings-view/issues/532?

**Comment by batjko** [comment]
Guys, as the OP I'm inclined to close this off. I have since seen this behavior with many other packages and it's most likely related to the Settings View issue @dessant has just linked to. Please subscribe to that issue instead.
