### ISSUE TITLE
Add support for NCAR Command Language (ncl)

### ISSUE THREAD

**Issue by julian-carpenter** [rgbkrk/atom-script#488]
from command line:

    ncl 'filename.ncl'

Highlighting Support is already implemented in Atom.
There is only one IDE (Netbeans) than can run
NCL scripts from the editor itself. So this would be a great
addition to Atom since many GeoScientists use NCL on a 
very regular Basis.

**Comment by rpavlick** [comment]
I've submitted a pull request https://github.com/rgbkrk/atom-script/pull/501 for this.

**Comment by rpavlick** [comment]
Fixed by https://github.com/rgbkrk/atom-script/commit/409545131f15c1c1dfa83e102c01306dfec56fe6

**Comment by julian-carpenter** [comment]
Thanks man ! Awesome job
