### ISSUE TITLE
Can't build any program on windows (Julia, Python)

### ISSUE THREAD

**Issue by niczky12** [rgbkrk/atom-script#491]
Hi, I've just downloaded Atom and wanted to build some Julia and Python scripts using script, but for some reason it fails to do anything with them.

I looked around the forums and found some people suggesting that it's something to do with the $PATH, but nothing works.

I get the following output when I try to build a julia script (this runs fine from the terminal)

```
Unable to run

julia
Is it in your PATH?

PATH: C:\Program Files\ImageMagick-6.9.1-Q16;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Adobe\AGL;C:\Program Files\Calibre2\;D:\Programs\Matlab\runtime\win64;D:\Programs\Matlab\bin;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Python34;C:\Python34\Scripts;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\LLVM\bin;C:\HashiCorp\Vagrant\bin;C:\Julia\bin;C:\Go\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Users\BNK\AppData\Local\atom\bin
```

I also tried changing ```init.coffee``` by adding ```process.env.PATH = "C:\\Julia\\bin"``` to no avail.

Starting atom from the command line also gives the same result.

Does anyone have any suggestions for this?

Thanks.

**Comment by niczky12** [comment]
Okay, after some headaches, I finally figured it out.

If anyone else is having the same issue as I and is unfortunate enough to use Windows then the solution is simple.
You need to run your scripts in the project folder! You can't open up a file outside the project folder and expect to build it.

Hope this helps you guys.

**Comment by Evmorov** [comment]
@niczky12 Thanks, it's helped me.
Just open the folder as a project where your script is.

**Comment by rgbkrk** [comment]
Ah, that project default folder change seems like it's been tripping a lot of people up based on the pile of issues sitting here. Thank you and sorry for all that.
