### ISSUE TITLE
Python in Windows PATH variable, but not recognized by Script

### ISSUE THREAD

**Issue by PMende** [rgbkrk/atom-script#499]
Currently, when I try to use Script to execute Python scripts on Windows 7, I get the following error message:

>Unable to run
>
>python
>Is it in your PATH?
>
>PATH: C:\Python34\;C:\Python34\Scripts;...

As you can see, Python is very clearly in the PATH. Indeed, it functions properly when called from Command Prompt:

>"Microsoft Windows [Version 6.1.7601]
>Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
>
>C:\Users\Patrick>python
>Python 3.4.3rc1 (v3.4.3rc1:69dd528ca625+, Feb  8 2015, 11:01:19) [MSC v.1600 32
>bit (Intel)] on win32
>Type "help", "copyright", "credits" or "license" for more information."

This is apparently a common enough issue. However, in my case it's particularly frustrating since Script *actually functioned properly* immediately after install. Obviously, I have no example of a successful execution of the package commands, because who makes notes about when something works as expected? I've already attempted to use the manual run commands with a direct link to the executable since this issue has arisen, but this produces the exact same error:

>Unable to run
>
>C:\Python34\python.exe
>Is it in your PATH?
>...

Anyway, if anyone has suggestions (aside from changing operating systems, thanks), I would appreciate it. I have already attempted reinstalling the package to no effect.

**Comment by jwpnet** [comment]
I was having the same issue with Window 7.  I finally solved the issue by running the command line as administrator, right click on cmd.exe and select "Run as Administrator".  Finally Script is able to execute.

**Comment by PMende** [comment]
After reinstalling Script, this is now working. Thanks very much for the suggestion!
