### ISSUE TITLE
Unable to run Python script

### ISSUE THREAD

**Issue by inhok996** [rgbkrk/atom-script#506]
I successfully installed atom and script. But I can't run python script at all(all python scripts has same error.)

I'm using Window 7 and python3.4. Plz help me.
![pythonerror](https://cloud.githubusercontent.com/assets/10493793/8649433/2ac8a8c2-29a5-11e5-8603-5c9789a02c96.png)

**Comment by rgbkrk** [comment]
Based on the double output, you need to fully restart and upgrade Atom if you can.

**Comment by EntilZha** [comment]
Closing due to age, no response, and lack of information
