### ISSUE TITLE
Unable to run any files

### ISSUE THREAD

**Issue by ThiconZ** [rgbkrk/atom-script#523]
After updating Atom I have been unable to run any files. I get the "Unable to run" "Is it in your PATH?" message in the Script panel. I've tried running both with Selection and File styles for Lua, Batch, and C files. I have tried going into my system Path variable and adjusting it manually to add and remove the locations of the compilers but that did not resolve the issue. I have also tried uninstalling and reinstalling Script.

Here is an image of what is given every time I attempt to run a file:
![image](https://cloud.githubusercontent.com/assets/6924950/9023157/0013560a-385e-11e5-8c38-4d080635dc5a.png)

I am able to run the compilers from a Command Prompt window just fine as well. 

I am running Atom v1.0.3 with Script v2.26.3 on Windows 7 Ultimate 64-bit.

**Comment by ThiconZ** [comment]
This issue has been resolved. It seems a computer restart is required after updating from Atom 1.0.2 to 1.0.3 for Script to work again. Tested on a VM running Atom 1.0.2, Script running fine. After upgrading it to 1.0.3 Script was unable to run anything. Once the VM was restarted Script was running everything fine once again.

Not sure if this is a Script related issue or an Atom issue.

**Comment by rgbkrk** [comment]
That's incredibly weird. Glad to hear it's working now!
