### ISSUE TITLE
language-babel has changed grammar string name

### ISSUE THREAD

**Issue by gandm** [rgbkrk/atom-script#529]
Hi, I'm the author of language-babel. Someone has reported an issue https://github.com/gandm/language-babel/issues/38 that appears to be related to a change of grammar string I made in my version 0.10.5. I did this to accommodate this PR https://github.com/gandm/language-babel/pull/36.

I also note another user has raised an issue here https://github.com/rgbkrk/atom-script/issues/528
that is most likely related.

 I note you use my old string name. I would do a PR but don't know if you want to leave the current string in place and add a new new one, or replace it.

Thanks.

**Comment by rgbkrk** [comment]
I'd like to stay current with whatever you're using, so fire that pull request over!

**Comment by rgbkrk** [comment]
Done in #530.
