### ISSUE TITLE
Current working directory is always the first project's

### ISSUE THREAD

**Issue by nickpetrovic** [rgbkrk/atom-script#543]
I have several projects opened into tree view (file explorer). Everyone one of my bash scripts in each project is saying the current working directory is that of my first project.

Consider the following projects in the tree view.
- Project0
- Project1

Now this is an example script in Project1

``` sh
#!/bin/bash
# Project1
pwd
# /Users/Nick/Projects/Project0
```

This breaks all of my working directory references. Workaround is to cd into my project's directory at the beginning of the script. 

Things I've tried and was able to replicate the issue:
- Not using symlinks for projects
- Adding a new project then testing
- Trying several projects and placing the script in subdirectories

**Comment by dinya** [comment]
@rgbkrk,

May be add option (checkbox) like this
```
Working directory:
- Use first project directory in the Tree view
- Use running script directory
```
will be useful feature?

I use Atom and atom-script for few projects simultaneously and I should remove projects from Tree view before running script from current project :(

**Comment by nixel2007** [comment]
I thought about these a few days ago too. 
I think it is make sense. 
@rgbkrk what do you think about placement of this option? Package-wide or run options?

**Comment by rgbkrk** [comment]
Package wide seems sensible, though I'm not a user here on this one.

**Comment by nixel2007** [comment]
I think there should be three options.
- Use first project directory in the Tree view
- Use running script's project path
- Use running script directory
