### ISSUE TITLE
Add Selection Based support for Java

### ISSUE THREAD

**Issue by jmw89** [rgbkrk/atom-script#551]
Try to run "script" run code package in atom but it says "Selection Based runner not available for Java." even tho the package says it support java language. Whats wrong?

**Comment by EntilZha** [comment]
Since its been a while closing since its a duplicate of #796, but if you still have issues respond with:
* Minimal java file that causes the issue
* Exact steps to reproduce
* Screenshots/Gifs of what is going wrong
