### ISSUE TITLE
Problem trying to install package Script

### ISSUE THREAD

**Issue by denisbao** [rgbkrk/atom-script#553]
I can't download the package Script in the the Settings view or in the command line. I'm new in programing and don't know Atom very well and really want to try this package.

Installing “script@2.26.4” failed.Hide output…
Unable to download https://www.atom.io/api/packages/script/versions/2.26.4/tarball: 503

PS: sorry for the bad english...

**Comment by rgbkrk** [comment]
Seems like Atom's service went out, that's fetchable right now.

You can also try running `apm develop script` to install it from git if it's some weird firewall issue.

**Comment by denisbao** [comment]
Tried running apm develop script, did not work:
"Request for package information failed: getaddrinfo ENOTFOUND"
I guess that is no longer available?

**Comment by rgbkrk** [comment]
Just a shot in the dark here... would you be able to set your DNS to the [Google Public DNS](https://developers.google.com/speed/public-dns/docs/using)?

That's a DNS error, which is *way* out of my control. I'll report this to @atom as well.

**Comment by denisbao** [comment]
Well... this was a headshot! Changing the DNS worked. Thanks rgbkrk!

**Comment by rgbkrk** [comment]
No prob.
