### ISSUE TITLE
Print statements for cmd+i don't always work for Python

### ISSUE THREAD

**Issue by JTFouquier** [rgbkrk/atom-script#568]
I'm using MacOS, atom 1.0.11, atom-script 2.26.4.  

When I use `cmd+i` for running the entire Python script, my print statements don't always show up (it will just say `[Finished in 0.082s]` or something.  So I often hit `cmd + i` several times.  I saw the issue for line by line printing, but felt this was different.  

Thanks!

**Comment by EntilZha** [comment]
Resolved by #700
