### ISSUE TITLE
Add support for Clojure

### ISSUE THREAD

**Issue by bordeltabernacle** [rgbkrk/atom-script#570]
Would this be possible?
Thanks in advance.

**Comment by ivanlemeshev** [comment]
+1

**Comment by rgbkrk** [comment]
What command would you run to run a Clojure file? Once you have that, it's a matter of adding it to lib/grammars.coffee.

**Comment by bordeltabernacle** [comment]
I've not had any success with this.  I'm new to Clojure and have hit the ceiling of my understanding.  I've tried adding the following to lib/grammars.coffee

```
Clojure:
    "File Based":
      command: "lein run"
      args: (context) -> [context.filepath]
```

For the command I have also tried `lein trampoline run` `lein repl` `lein trampoline run -m clojure.main`, this last one being the command Sublime Text uses.  I have also tried these with the lein repl running in the background.
Each time I get the following error.

```
Unable to run

lein run
Is it in your PATH?

PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

And lein is in my path.

```
$ which lein
/usr/bin/lein
```

**Comment by rgbkrk** [comment]
Make sure to both upgrade to the latest Atom as well as launch atom via the command line `atom .`

(I can tell from the error message this is an older release)

**Comment by bordeltabernacle** [comment]
Still no dice.

```
Unable to run

lein trampoline run -m clojure.main
Did you start Atom from the command line?

  atom .
Is it in your PATH?

PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

```
$ atom .
$ atom -v
1.0.19
```

**Comment by Stormherz** [comment]
@rgbkrk @bordeltabernacle AFAIK lein is an additional tool (very popular among clojure developers) for clojure project management. It is easier to implement lein support than plain clojure (lein is located in PATH, while running custom clojure file would require to specify location of clojure.jar).

So, in fact, we have a somewhat hard decision to make - should we support lein tool (which will allow advanced control of runnina clojure scripts/apps) or should we require user to move clojure.jar to PATH or to specify it through run options.
