### ISSUE TITLE
Node - Unable To Run Script

### ISSUE THREAD

**Issue by DylanLenz** [rgbkrk/atom-script#580]
I keep getting this error everyonce in a while. I am opening from my terminal now, and still having the issue. Any idea?

Unable to run

node
Is it in your PATH?

PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin

**Comment by DylanLenz** [comment]
I fixed it by updating Node.js

**Comment by lincolnfrias** [comment]
In my case (Linux, Ubuntu), the solution was to install node-legacy besides nodejs. I just did:
`sudo apt install  node-legacy`
