### ISSUE TITLE
Cannot run python

### ISSUE THREAD

**Issue by trongdth** [rgbkrk/atom-script#586]
The python code will not run if there is an "import" another python file. Is there any workaround on this?

Thanks
Trong

**Comment by timthejiang** [comment]
Hi Trong,

I would need more information:
- Copy and paste the line of `import` code.
- Copy and paste the error.
- What's your directory structure?

Tim

**Comment by trongdth** [comment]
Hi Tim,

Here is a sample of structure of my project

projects
  |_ _ robot
           |_ _ manager
                       |_ _ __init__.py
                       |_ _ error_msg.py
           |_ _ os_manager
                       |_ _ __init__.py
                       |_ _ os.py
 
I've configured PYTHONPATH is the path to "projects" folder and inside my os.py I does something like this one: from rotbot.manager.error_msg import *

But when running it's always through the error: ImportError: No module named rotbot.manager.error_msg

Thanks
Trong

**Comment by CrandellWS** [comment]
You need an empty  __init__.py  in robot

**Comment by rgbkrk** [comment]
@timthejiang and @CrandellWS thanks for debugging and helping out!

**Comment by EntilZha** [comment]
Going to `Script: Run Options` and changing working directory should fix it.

Closing due to age/no response, reopen if you still have issues though
