### ISSUE TITLE
Unable to run python Windows 7

### ISSUE THREAD

**Issue by codekraft-studio** [rgbkrk/atom-script#598]
I don't know why it's giving this error:

Unable to run

python
Is it in your PATH?

PATH: C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;

I tried with Python 3.5 too but same error.

I open atom from AppData\Local\atom\bin\atom.cmd

**Comment by s-trooper** [comment]
welcome, this is at least 4 issue to the same problem only on the first page in tracker :)

**Comment by cbranca** [comment]
I have the same problem with Perl. Perl path is in the Path variable and I run Atom from command line with administrator privileges.

**Comment by rgbkrk** [comment]
Make sure to run `atom .` from the directory of the project you're running in. Atom changed semantics from `atom` to `atom <project-dir>` for context of where it's running from by default.
