### ISSUE TITLE
Add File Based support for C  

### ISSUE THREAD

**Issue by khanhle10** [rgbkrk/atom-script#603]
##### Platform: `linux`
---File Based runner not available for C++.

If it should exist, add an issue on GitHub, or send your own pull request.

**Comment by rgbkrk** [comment]
Currently this works on OS X using `xcrun`. How would it work for Linux? C isn't interpreted, so we'd have to do some light trickery to build and run `a.out` I suppose.

**Comment by khanhle10** [comment]
Alright thank you.


________________________________

**Comment by EntilZha** [comment]
Duplicate of #454
