### ISSUE TITLE
Got error when I try to run js code

### ISSUE THREAD

**Issue by mattma** [rgbkrk/atom-script#61]
I just installed the script plugin today on the latest atom editor 0.69.

I have a file named `test.js`, I defined a test function like it

```
function test() {
    console.log('hello world');
}
test();
```

Then I hit  cmd-i, I got an error

```
 execvp(): No such file or directory
```

Tried in the readme shell script ls example, it did not work for me at all. I am using the script@2.0.2 , is there any special setup to use this plugin? thanks

**Comment by jbavari** [comment]
I've just worked around this issue on OSX.

The way I solved it was by using the [fix-path](https://www.npmjs.com/package/fix-path) module to adjust my path when running from the app file.

Hope this helps any other users with this issue.

**Comment by oddysee** [comment]
@jbavari How did you _use_ fix-path for the script plugin? Is there a pull request or branch I can use?

**Comment by BramVanroy** [comment]
All of the discussion above seems Linux-centred. However, I'm happily running on W10 and I'm not entirely sure how I can start Atom from cmd, or with custom parameters on an icon, so the package would work. Any suggestions?

**Comment by safir187** [comment]
W10 +1

**Comment by hurrymaplelad** [comment]
@oddysee Wrapped up [fix-path](https://www.npmjs.com/package/fix-path) as an [atom package](https://atom.io/packages/atom-fix-path).  You should just be able to `apm install atom-fix-path` or install it from the settings pane.  Thanks @jbavari for the suggestion.

**Comment by naomik** [comment]
+1 @rgbkrk for

```coffee
# init.coffee
process.env.PATH = ['/usr/local/bin', process.env.PATH].join(':')
```

but who knows what `PATH` is set to by default. I prefer just being totally explicit and setting my entire `PATH`. That way if a binary can't be found, I know precisely which directories need to be added.

```coffee
# init.coffee
process.env.PATH = [
  "/usr/local/bin",
  "/usr/bin",
  "/bin"
].join(":")
```

Less is more™

**Comment by rgbkrk** [comment]
@naomik On Mac at least, `PATH` gets set by launchctl. If you want to see what it gets set to on startup, put

```
alert(process.env.PATH)
```

in your init.coffee and see what you get back.

**Comment by naomik** [comment]
@rgbkrk yeah I still prefer to just set what's required. I do the same in my `.zshrc` but maybe that's me being overly controlling.

**Comment by rgbkrk** [comment]
Yeah, I prefer to use what's in my bashrc. The problem lies in how Atom is launched (or restarted after an upgrade...) :unamused:

**Comment by ersiner** [comment]
You may use [osx-env-sync](https://github.com/ersiner/osx-env-sync) to solve this problem on OS X for all applications in the proper way.

**Comment by turotulco** [comment]
Windows 7. I just went into MyComputer, chose Advanced System Settings, and pressed the button marked Environment Variables. Path is the top environment variable. Add ";C:\Python" to the end of the path (or the beginning; or whatever your python path is named). This is the environment that will be loaded every time a command prompt is spawned.

**Comment by ToSeven** [comment]
window10  I just run c program but script generate some terrible things , I use google to solve it ,but there is nothing so can you help me?

![default](https://cloud.githubusercontent.com/assets/14891443/21493964/2ac543ec-cc49-11e6-94a3-ab68f879bb6c.PNG)

**Comment by danielbayley** [comment]
Just to add _another_ solution… there's also the _[env-from-shell](https://atom.io/packages/env-from-shell)_ package.

**Comment by SarbajitNandy** [comment]
I'm a pc user. I have downloaded atom recently, and want to set it up for Python coding. Though I have already downloaded 'Script' for run codes. but facing a great problem at the time of running . though the whole code is perfect, getting this message  **"Python is not recognized as an internal or external command"**.       plz help me to solve this.

**Comment by miromarszal** [comment]
A workaround for Win10:

1. Right-click on the Atom shortcut
2. Go to "Properties"
3. Replace the path in "Target" with `cmd /C atom`

A side effect: the terminal window stays open.

**Comment by danPadric** [comment]
>  **miromarszal commented 6 days ago**
> ### 
> A workaround for Win10:
> 
>     Right-click on the Atom shortcut
>     Go to "Properties"
>     Replace the path in "Target" with cmd /C atom
> 
> A side effect: the terminal window stays open.

Hi. Let us consider this proposal. How about creating a BAT file?..

1. Right-click on the Atom shortcut
2. Go to "Properties" of the shortcut
3. Copy the entry in "Target" 
4. Open a text editor such as Notepad
5. Put in this text file the "Target" copied in (3)
6. Insert the line _@echo off_ before it.
7. Save & close the text file as (example) openAtom.bat in the same directory as "Target"
8. Replace the "atom.exe" with "openAtom.bat" in the "Target" of (3).

The command prompt does open,but does not remain open.

Helpful?
- Dan

**Comment by miromarszal** [comment]
I should have thought about this one, works like a charm.

**Comment by Kristi92** [comment]
Error
Line Number Based runner not available for JavaScript.

If it should exist, add an issue on GitHub, or send your own pull request.

**Comment by Kristi92** [comment]
can anyone help me with this issue please
?

**Comment by MStonehouse** [comment]
For Ubuntu and Linux Mint.

Hello bhflm.

Just ran into the same problem you had. This might help.

If you installed the flatpack version from software manager Atom won't be able to find node. 

Uninstall Atom. 

Go to https://atom.io/ and download the .deb version.

Once downloaded double click on the deb download. A popup window will open. Click on install package. 

Not only will Atom now recognize the path to node, your install is now less than 1GB (flatpack is 3.4GB)

**Comment by trbielec** [comment]
Workaroud for python3:

#1787

> If you want to use Python3 by default, you can open Atom Settings, Atom→Preferences→Open Config Folder, and open.atom/packages/script/lib/grammars/python.coffee, Changing python to python3 under 'Selection Based' and 'File Based', saving it.

**Comment by MCilento93** [comment]
Nothing specific for conda?
I would like to change the init.coffee suitably to startup atom (when launched by icon) in pre-activated conda folder.
Thank you

**Comment by omarflight** [comment]
how to fix this
'python' is not recognized as an internal or external command,
operable program or batch file.

**Comment by MCilento93** [comment]
> how to fix this
> 'python' is not recognized as an internal or external command,
> operable program or batch file.

if you have python installed from official release, you should not have issues.
If you are using conda you can open atom from pre-activated cmd

**Comment by LuciferChase** [comment]
I dig through this thread and tried running atom from the cmd itself still I am unable to run any Kotlin file. A little help?
![image](https://user-images.githubusercontent.com/48217707/104589124-6c2afa00-568f-11eb-96ed-40a0042ccca3.png)

**Comment by M5planetX** [comment]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description



### Steps to Reproduce

1. Install atom
2. Install GitHub for Windows
3. Install atom-script
4. Run atom

**Expected behavior:**

normal atom welcome screen

**Actual behavior:**



### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [script](https://github.com/atom-ide-community/atom-script) package 3.32.2


### Stack Trace

Failed to activate the script package

```
At Cannot find module 'temp'
Require stack:
- C:\Users\Pc\.atom\packages\atom-script-3.32.2\lib\grammar-utils.js
- C:\Users\Pc\.atom\packages\atom-script-3.32.2\lib\grammars\index.js
- C:\Users\Pc\.atom\packages\atom-script-3.32.2\lib\grammars.js
- C:\Users\Pc\.atom\packages\atom-script-3.32.2\lib\code-context-builder.js
- C:\Users\Pc\.atom\packages\atom-script-3.32.2\lib\script.js
- C:\Users\Pc\AppData\Local\atom\app-1.60.0\resources\app.asar\static\index.html

Error: Cannot find module 'temp'
Require stack:
- C:\Users\Pc\.atom\packages\atom-script-3.32.2\lib\grammar-utils.js
- C:\Users\Pc\.atom\packages\atom-script-3.32.2\lib\grammars\index.js
- C:\Users\Pc\.atom\packages\atom-script-3.32.2\lib\grammars.js
- C:\Users\Pc\.atom\packages\atom-script-3.32.2\lib\code-context-builder.js
- C:\Users\Pc\.atom\packages\atom-script-3.32.2\lib\script.js
- C:\Users\Pc\AppData\Local\atom\app-1.60.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:157942)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149229)
    at /packages/atom-script-3.32.2/lib/grammar-utils.js:6:24)
    at /packages/atom-script-3.32.2/lib/grammar-utils.js:128:28)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149229)
    at /packages/atom-script-3.32.2/lib/grammars/index.js:12:24)
    at /packages/atom-script-3.32.2/lib/grammars/index.js:614:29)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149229)
    at /packages/atom-script-3.32.2/lib/grammars.js:11:22)
    at /packages/atom-script-3.32.2/lib/grammars.js:46:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149913)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
```

### Commands

```
```

### Non-Core Packages

```
script 3.32.2 
```

### Additional Information


Hello all,
I've installed atom, GitHub for windows, and the atom-script-3.32.2 package successfully but I am unable to run any code using ctrl+shift+B and whenever I open atom I get this message.
Pls help
