### ISSUE TITLE
can't run javascript-code

### ISSUE THREAD

**Issue by grrgrrbla** [rgbkrk/atom-script#620]
I get the following error whenever I try to execute javascript-code:

"Unable to run

node
Did you start Atom from the command line?

  atom .
Is it in your PATH?

PATH: /home/daniel/anaconda3/bin:/home/daniel/anaconda3/bin:/home/daniel/bin:/usr/local/texlive/2014/bin/x86_64-linux:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:usr/bin/atom:usr/bin/nodejs:/usr/bin/atom:/usr/bin/nodejs"

I tried to start atom from the terminal (typing atom .), I have nodejs installed and can use it just fine inside the terminal, I looked at other related issues, nothing worked, I can run python code without any issues. I am using linux mint (3.13.0-37-generic).
It works just fine when I use "configure run options" and type the path of nodejs into the option "Command"

**Comment by lincolnfrias** [comment]
In my case (Linux, Ubuntu), the solution was to install node-legacy besides nodejs. I just did:
`sudo apt install  node-legacy`
