### ISSUE TITLE
Add support for Octave

### ISSUE THREAD

**Issue by ArmlessJohn404** [rgbkrk/atom-script#621]
i'll take a quick look, if It's easy to implement I'll send a PR

**Comment by rgbkrk** [comment]
Add it on to lib/grammars.coffee, following the other languages practices. Happy to welcome it!

**Comment by ArmlessJohn404** [comment]
Done! 
Still looking for stdin support, that will be awesome!

**Comment by rgbkrk** [comment]
That would be awesome. You're better off using [Hydrogen](https://github.com/willwhitney/hydrogen) for interactivity, with an [Octave kernel](https://github.com/calysto/octave_kernel).

**Comment by ArmlessJohn404** [comment]
Hooray! thanks for the tips

**Comment by pashute** [comment]
I run a .m file and get: 'octave' is not recognized as an internal or external command,
operable program or batch file.
[Finished in 0.054s]

I have octave installed but it's not in the path. 

Can I set the options (^shift P: script run options) somehow to point to my current dir (c:\dev\octavetests\trial1)
and to octave (C:\Octave\Octave-4.2.1\bin) ? 
What do I need to do?
