### ISSUE TITLE
Uncaught TypeError: Cannot read property  TOSTRING  of undefined

### ISSUE THREAD

**Issue by MaxGraey** [rgbkrk/atom-script#629]
Enter steps to reproduce below:  1. ... 2. ... **Atom Version**: 1.0.19 **System**: Mac OS X 10.11.1 **Thrown From**:  script  https://github.com/rgbkrk/atom-script  package, v3.0.1 ### Stack Trace Uncaught TypeError: Cannot read property  TOSTRING  of undefined     At /Users/maxgraey/.atom/packages/script/lib/script-view.coffee:34 TypeError: Cannot read property  TOSTRING  of undefined at SCRIPTView.module.exports.SCRIPTView.setHeaderAndShowExecutionTime  /Users/maxgraey/.atom/packages/script/lib/script-view.coffee:34:53  at SCRIPTView.setHeaderAndShowExecutionTime  /Users/maxgraey/.atom/packages/script/lib/script-view.coffee:1:1  at /Users/maxgraey/.atom/packages/script/lib/view-runtime-observer.coffee:15:13 at Emitter.module.exports.Emitter.emit  /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11  at Runner.module.exports.Runner.onExit  /Users/maxgraey/.atom/packages/script/lib/runner.coffee:67:14  at /Users/maxgraey/.atom/packages/script/lib/runner.coffee:1:1 at triggerExitCallback  /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18 at Socket. anonymous>  /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18  at emitOne  events.js:82:20  at Socket.emit  events.js:169:7  at Pipe._onclose  net.js:467:12      ### Commands     -6:44.1.0 emmet:insert-formatted-line-break-only  atom-text-editor.editor.is-focused  -6:44.1.0 editor:newline  atom-text-editor.editor.is-focused  -6:44 emmet:insert-formatted-line-break-only  atom-text-editor.editor.is-focused  -6:44 editor:newline  atom-text-editor.editor.is-focused  2x -6:38.6.0 core:move-left  atom-text-editor.editor.is-focused  2x -6:36.6.0 core:move-right  atom-text-editor.editor.is-focused  -6:35.3.0 core:save  atom-text-editor.editor.is-focused  -6:35.1.0 script:run  atom-text-editor.editor.is-focused  2x -6:28.4.0 core:backspace  atom-text-editor.editor.is-focused  -6:27.5.0 core:save  atom-text-editor.editor.is-focused  -6:26.9.0 emmet:insert-formatted-line-break-only  atom-text-editor.editor.is-focused  -6:26.9.0 editor:newline  atom-text-editor.editor.is-focused  -6:26.4.0 core:save  atom-text-editor.editor.is-focused  -3:45.8.0 settings-view:check-for-package-updates  atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-fusion-syntax.theme-one-dark-ui  -3:23.3.0 settings-view:OPEN  atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-fusion-syntax.theme-one-dark-ui  -0:04.2.0 script:run  atom-text-editor.editor.is-focused      ### Config    json { core : { themes :   one-dark-ui , atom-dark-fusion-syntax  , disabledPackages :   language-go , language-clojure , language-toml , atom-path-walker-2 , typeWRITEr-sounds , preview-plus , docblockr , .bin , file-icon-supplement   }, script : { enableExecTime : false } }     ### Installed Packages    coffee # User Sublime-Style-Column-Selection, v1.3.0 atom-alignment, v0.12.1 atom-beautify, v0.28.14 atom-dark-fusion-syntax, v0.7.0 atom-html-preview, v0.1.11 atom-jade, v0.3.0 atom-typescript, v7.5.0 autoclose-html, v0.19.0 autocomplete-clang, v0.8.7 autocomplete-glsl, v0.2.3 autocomplete-modules, v1.3.0 autocomplete-plus-python-jedi, v0.3.6 autocomplete-python, v0.7.0 change-case, v0.6.0 color-picker, v2.0.13 emmet, v2.3.13 file-icons, v1.6.11 flex-tool-bar, v0.5.0 highlight-selected, v0.10.1 language-babel, v0.15.7 language-dots, v0.0.4 language-glsl, v2.0.1 language-vue, v0.3.0 linter, v1.8.1 linter-csslint, v1.1.0 linter-htmlhint, v0.1.1 linter-jshint, v1.2.1 linter-shellcheck, v1.0.2 markdown-preview-plus, v2.2.2 react, v0.12.10 save-session, v0.15.7 script, v3.0.1 tool-bar, v0.1.9 vue-autocompile, v0.0.1 # Dev No dev packages

**Comment by SamStrawbridge** [comment]
this fix has been tested, issue can be closed :+1:
