### ISSUE TITLE
Add support for JavaScript (JSX)

### ISSUE THREAD

**Issue by darrenscerri** [rgbkrk/atom-script#630]
Would it be possible to add support for the Javascript (JSX) grammar and run code using node?

**Comment by GeneLocklin** [comment]
Support for this feature already exists, using [language-babel](https://github.com/gandm/language-babel) and [babel-plugin-syntax-jsx](https://github.com/babel/babel/tree/master/packages/babel-plugin-syntax-jsx).

**Comment by LucasArruda** [comment]
@GeneLocklin I think @darrenscerri meant support for evaluating JSX as Javascript, not syntax provided by babel.

**Comment by dudeinthemirror** [comment]
+1

**Comment by rgbkrk** [comment]
We should probably just alias this one to do the same as the node.js setup.

**Comment by danielbayley** [comment]
@darrenscerri This is implemented [here](https://github.com/rgbkrk/atom-script/blob/master/lib/grammars/javascript.js#L36).
