### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by SamStrawbridge** [rgbkrk/atom-script#635]
[Enter steps to reproduce below:]

1. disable setting "Output the time it took to execute the script" 
2. run the python in step 3
3.
listA = [2.2, 2.3, 2.4, 3.2, 3.3, 3.4, 4.2, 4.3, 4.4, 5.2, 5.3, 5.4, 6.2, 6.3, 6.7]
listB = [1.1, 1.3, 3.2, 4.1, 2.2, 3.3, 3.1, 4.3, 5.3, 5.1, 4.2, 5.2, 6.1, 6.2, 6.3]

def combine(listIn):
    listOut = []
    c = 0
    for i in listIn[0:len(listIn)-1]:
        c = c + 1
        for j in listIn[c:len(listIn)]:
            listOut.append((i, j))
    return listOut

def compare(list1, list2):
    counter = 0
    for i in list1:
        if i in list2:
            counter = counter + 1
    return counter/len(list1)        

print(round(compare(combine(listA), combine(listB)), 3))

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package, v3.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of undefined

```
At /Users/samstrawbridge/.atom/packages/script/lib/script-view.coffee:34

TypeError: Cannot read property 'toString' of undefined
    at ScriptView.module.exports.ScriptView.setHeaderAndShowExecutionTime (/Users/samstrawbridge/.atom/packages/script/lib/script-view.coffee:34:53)
    at ScriptView.setHeaderAndShowExecutionTime (/Users/samstrawbridge/.atom/packages/script/lib/script-view.coffee:1:1)
    at /Users/samstrawbridge/.atom/packages/script/lib/view-runtime-observer.coffee:15:13
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Runner.module.exports.Runner.onExit (/Users/samstrawbridge/.atom/packages/script/lib/runner.coffee:67:14)
    at /Users/samstrawbridge/.atom/packages/script/lib/runner.coffee:1:1
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
```

### Commands

```
     -9:10.4.0 core:paste (atom-text-editor.editor.is-focused)
     -9:05.7.0 grammar-selector:show (atom-text-editor.editor)
  4x -8:55.6.0 script:run (a.inline-block)
     -8:46.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -8:45.9.0 script:run (atom-text-editor.editor.is-focused)
 18x -7:37.4.0 core:move-right (atom-text-editor.editor.is-focused)
  8x -7:33.6.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -7:29.5.0 script:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "script": {
    "enableExecTime": false
  }
}
```

### Installed Packages

```coffee
# User
script, v3.0.1

# Dev
No dev packages
```

**Comment by SamStrawbridge** [comment]
Thanks for the fix :+1:

**Comment by MaxGraey** [comment]
Don't mention it)

**Comment by chrwi** [comment]
When will an update be pushed?

**Comment by SamStrawbridge** [comment]
@chrwi It''s been merged, so I guess we are waiting for the next release

**Comment by SamStrawbridge** [comment]
fix tested, it's working

**Comment by rgbkrk** [comment]
Thanks for the issue stewardship @SamStrawbridge. Adding you on as a maintainer to help.
