### ISSUE TITLE
Can't run JS - "Unable to run node"

### ISSUE THREAD

**Issue by Rain288** [rgbkrk/atom-script#672]
Greetings! I know there are several issues on this but mine is still not working. I'm running the latest version of Atom, latest version of node, and latest version of the package. It is also in my path, as seen on the file attached. I am running atom through the "atom" command and I have tried putting the path to my node manually through the run settings (alt+ctrl+shift+o), and then it said it couldn't run that. I am not sure what I'm supposed to do.
![nwahngu](https://cloud.githubusercontent.com/assets/11058975/11506815/e3e4afae-9859-11e5-9efc-eb60faf98636.png)

**Comment by petersirka** [comment]
I have same problem on OSX and for me works:

`Atom Menu` --> `Open Your Init Script`

__Write path:__
```javascript
process.env.PATH = [
  "/usr/local/bin",
  "/usr/bin",
  "/bin"
].join(":")
```

Thanks.

**Comment by LDubya** [comment]
^ worked for me

**Comment by lincolnfrias** [comment]
In my case (Linux, Ubuntu), the solution was to install node-legacy besides nodejs. I just did:
`sudo apt install  node-legacy`
