### ISSUE TITLE
Not able to run Java program

### ISSUE THREAD

**Issue by Omkar-Shetkar** [rgbkrk/atom-script#674]
I have installed scripts package to be able to run Java program on
Atom editor. But still not able to run it. Getting following error
message:

'bash' is not recognized as an internal or external command, operable
program or batch file

What could be missing here?
I am using Windows 7 OS. Same editor with same package, runs on Ubuntu without any issues.

Please clarify.

**Comment by Nav31** [comment]
Most likely Java isn't in your executable path for windows 
https://www.java.com/en/download/help/path.xml

**Comment by XSStudio** [comment]
Please use the filter bar to check if there is an answer to your issue already: https://github.com/rgbkrk/atom-script/issues/481 . The creator of atom script does not intend to make the code cross-platform, so you have to manually edit the source code if you're on Windows.

**Comment by Omkar-Shetkar** [comment]
It works with following modifications:
- Ensure Java path is appended to PATH variable in environment variables.
- I had git bash in windows system. https://git-scm.com/downloads
- Set the git bash path in environment variables.
Now, able to run Java from atom editor. :)

As suggested by others, cygwin could be other better alternative for bash.

**Comment by EntilZha** [comment]
Looks like this issue is resolved then, reopen if thats not the case
