### ISSUE TITLE
Add support for HTML

### ISSUE THREAD

**Issue by tikasan** [rgbkrk/atom-script#692]
<HTML>
<HEAD>
<TITLE></TITLE>
<SCRIPT language="JavaScript">

</SCRIPT>
</HEAD>
<BODY bgcolor="#ffffff">
下のボタンをクリックすると確認ウィンドウが表示されます<BR><BR>
<INPUT type="button" value="TOPページに戻る" onClick="cfm()">
</BODY>
</HTML>

**Comment by rgbkrk** [comment]
Dupe of #80, though we'll never be able to run HTML as a script. Need to use a preview pane for that.
