### ISSUE TITLE
Failed to run java

### ISSUE THREAD

**Issue by fobys** [rgbkrk/atom-script#703]
i got this situation....
but i don't know why....
I have already set java path & bash
![2015-12-22 22 59 23](https://cloud.githubusercontent.com/assets/1619609/11957936/b8845dda-a8ff-11e5-808a-b308231c48ca.png)

**Comment by fobys** [comment]
....I found what's wrong.....class name should be same as file name...

**Comment by Stormherz** [comment]
@fobys should we close the issue, since problem is solved?

**Comment by rgbkrk** [comment]
Thanks!
