### ISSUE TITLE
Why can`t read or open file using php function?

### ISSUE THREAD

**Issue by anlimas** [rgbkrk/atom-script#706]
I'm try to open or read file by fopen, readfile functions but getting 
Warning: readfile(data.txt): failed to open stream: No such file or directory in ...\fopen.php on line 3
<?
readfile("data.txt");
echo "\n";

In sublime it work fine?

**Comment by Stormherz** [comment]
@anlimas that's probably because your working directory is not set properly and that is not related to script plugin. Try running atom with 'atom .' command from the directory, where you have data.txt
