### ISSUE TITLE
How to config it to support C++ 11?

### ISSUE THREAD

**Issue by ChenZhongPu** [rgbkrk/atom-script#712]
As the title, `how to config it to support C++ 11 code ?`

**Comment by AriaFallah** [comment]
@ChenZhongPu 

Go to ~/.atom/packages/script/lib/grammers.coffee

Go to the C++ section (ctrl-f c++):

Then change this line:

```coffeescript
args: (context) -> ['-c', "xcrun clang++ -fcolor-diagnostics -Wc++11-extensions // other stuff
```
to this:

```coffeescript
args: (context) -> ['-c', "xcrun clang++ -fcolor-diagnostics -std=c++11 -stdlib=libc++ // other stuff
```

basically add `-std=c++11 -stdlib=libc++` and remove `-Wc++11-extensions`

**Comment by EntilZha** [comment]
Closing since there has been no response from issue author in more than a month, reopen if you still need help

**Comment by debashish05** [comment]
I am unable to find this directory "~/.atom/packages/script/lib/grammers.coffee" i am using windows.
it have no folder for script under  package folder.Need help.
