### ISSUE TITLE
Java code not found

### ISSUE THREAD

**Issue by RolandBrake** [rgbkrk/atom-script#722]
i tried to run simple hello world java program on windows 7 but this error appeared any help :

javac: file not found: helloWorld.java
Usage: javac <options> <source files>
use -help for a list of possible options
[Finished in 0.329s]

**Comment by HiggsWRX** [comment]
You do not have the JDK in your PATH. What OS are you running?

**Comment by EntilZha** [comment]
Need more info to help. Given that its been over a month without reply, closing
