### ISSUE TITLE
Add support for HTML

### ISSUE THREAD

**Issue by stephengfriend** [rgbkrk/atom-script#724]
Please add support for displaying HTML in the console.

It could just render it as plain text, respecting only new lines and `<br>` tags. It could reasonably ignore all javascript tags, style sheets, and any other markup.

**Comment by rgbkrk** [comment]
@smashwilson revealed to me that he was the :trollface: initiator.

It would make some sense to use a webview or iframe to render their HTML. Another option is opening it in a browser, though not every feature of the web can be used with `file://` as the protocol.

On a separate note, I should file yet another issue for deduping before suggesting creating an issue.

**Comment by stephengfriend** [comment]
+1

**Comment by smashwilson** [comment]
Ohh ooh or maybe you could exec `links` and bind stdout/stdin within the output pane :stuck_out_tongue_winking_eye:

**Comment by rgbkrk** [comment]
Even better.

*/me bans Ash*

**Comment by stephengfriend** [comment]
@smashwilson's solution would be acceptable.

**Comment by smashwilson** [comment]
By the way, if you actually _did_ want to open the page, [here's the Electron API](http://electron.atom.io/docs/v0.36.0/api/shell/#shell-openexternal-url) that can do that in a cross-platform way.

**Comment by stephengfriend** [comment]
putting aside the :trollface: , that wouldn't be a terrible way to fix the "I can run HTML plz!?"

**Comment by rgbkrk** [comment]
*/me Re-enables Ash*

That seems pretty nice. Hopefully a URL like this is opened later today. :wink:

```coffeescript
shell.openExternal(
  'https://github.com/rgbkrk/atom-script/compare/master...smashwilson:html-support?expand=1'
)
```
