### ISSUE TITLE
Windows Selection Based Python Not Working

### ISSUE THREAD

**Issue by danisant1** [rgbkrk/atom-script#729]
Selection based not working: 
<img width="452" alt="not_working_python" src="https://cloud.githubusercontent.com/assets/16651582/12239424/aed413d2-b856-11e5-981d-18c0e7fdd135.PNG">

Expected output "End of line.", nothing returned. Version 1.3.3 of Atom; Version 3.4.0 of Script

Running entire code works. It is just selection based that causes the problem.
<img width="448" alt="working_python" src="https://cloud.githubusercontent.com/assets/16651582/12239425/aed62f3c-b856-11e5-8309-5ccc8b40fe13.PNG">

**Comment by danisant1** [comment]
Now using Version 1.5.2 of Atom and Version 3.5.1; bug is still present.

**Comment by rcassani** [comment]
Same here Win10, Atom 1.12.3,  Script 3.11.1
This Issue is the same as Issue #955

**Comment by koslX** [comment]
I have the same issue Windows 7 Atom 1.34.0 x64 Script 3.18.1...
