### ISSUE TITLE
Add support for HTML

### ISSUE THREAD

**Issue by yask123** [rgbkrk/atom-script#737]
On pressing CMD+I , it should open browser

**Comment by SamStrawbridge** [comment]
I may be wrong (and someone please correct me if I am), but seems out of script's ball park, would a package like https://github.com/gabceb/atom-web-view not better suit your requirement?  Was there a particular use case you had in mind?

**Comment by yask123** [comment]
Yea, it does suit my requirement and I am currently using it. It would be nice it this feature was integrated in this extension only.

**Comment by EntilZha** [comment]
Marking as duplicate of #330 and/or #724, there is a similar discussion there
