### ISSUE TITLE
Add support for gnuplot

### ISSUE THREAD

**Issue by adamabernathy** [rgbkrk/atom-script#744]
How do I add support for a file type?

**Comment by nixel2007** [comment]
Hi, @adamabernathy! You can check through the [grammars.coffee](https://github.com/rgbkrk/atom-script/blob/master/lib/grammars.coffee) file, it's pretty simple.

**Comment by adamabernathy** [comment]
Cool, I figured that out now, just trying to get Atom to recognize it.

**Comment by Luthaf** [comment]
This is how I have done it: 

(1) Add the following at the end of `grammars.coffee`
```coffee
  gnuplot:
    "File Based":
      command: "gnuplot"
      args: (context) -> ['-p', context.filepath]
```

(2) Add the following at the beginning of your gnuplot scripts

```gnuplot
cd system("dirname " . ARG0)
```

(3) Enjoy your graphs!

**Caveats:** this only works for gnuplot > 5.0, and UNIX.

**Comment by nixel2007** [comment]
@luthaf you can make a PR with your changes

**Comment by Luthaf** [comment]
I would prefer to get the directory name of the current file using Atom API, but I do not find how to do this in the docs. Do you have a clue ?

**Comment by nixel2007** [comment]
sorry, i missed the second part. why do you need to do something in you file?

**Comment by Luthaf** [comment]
Because the gnuplot scripts can reference data files which are loaded relatively to the current directory. 

In the simplest case, people would use it as `gnuplot my_script.gp`, where `my_script.gp` contains `plot "datafile.data"`. Gnuplot will look for `datafile.data` in the same directory as `my_script.gp` . Then if atom was not launched from the exact same diectory as `my_script.gp`, gnuplot will fail.

And `cd system("dirname " . ARG0)` change the current directory to the directory containing the file use as command line parameter.

**Comment by nixel2007** [comment]
@Luthaf if i understand the package code right, you can specify the "workingDirectory" property in grammars.coffee.

You can define this with
```coffee
  gnuplot:
    "File Based":
      command: "gnuplot"
      args: (context) -> ['-p', context.filepath]
      workingDirectory: ->
        editor = atom.workspace.getActivePaneItem()
        file = editor?.buffer.file
        return file?.path
```

Please, try.

**Comment by Luthaf** [comment]
The code in `workingDirectory` does not seems to be executed at all. I do not get anything in the console when adding `console.log("here")`.

**Comment by nixel2007** [comment]
ah. it's not called as a function.
try 
```coffee
workingDirectory: atom.workspace.getActivePaneItem()?.buffer.file?.path
```

**Comment by Luthaf** [comment]
Not better. But what is strange is that even when I use 

```coffee
workingDirectory: "/"
```

gnuplot still gives me the project root when I use the `pwd` command.

**Comment by nixel2007** [comment]
hm... maybe @rgbkrk can help us?
how can we set the cwd in grammars.coffee?

**Comment by rgbkrk** [comment]
Thanks for looking into ways to do this. I'm unfamilar with the right way to do this as well. Perhaps grammars.coffee needs yet another extension point?

**Comment by nixel2007** [comment]
@rgbkrk in ideal world there should be 5 fields in grammars.coffee, cause you have 5 fields in script-options. Adding at least workingDirectory could help with this current issue and could help in future. 

Could you add some logic with reading this property to place, where the grammars.coffee is being parsed?

**Comment by rgbkrk** [comment]
I'm not going to be able to work on that, happy to merge work from someone that does it.

**Comment by nixel2007** [comment]
looks like i've done it. pr's incoming

**Comment by nixel2007** [comment]
correct line (when #832 will be merged):
```coffee
workingDirectory: atom.workspace.getActivePaneItem()?.buffer.file?.getParent().getPath()
```

**Comment by Luthaf** [comment]
Thanks!

**Comment by nixel2007** [comment]
@Luthaf PR was merged. You can provide your PR with gnuplot support.
Please add language in alphabetical order.
