### ISSUE TITLE
I cannot run Python commands in script :(

### ISSUE THREAD

**Issue by Pranav-7** [rgbkrk/atom-script#749]
First of all, let me tell you some things:
- I am very new
- I don't know most of code and programming terminology
- I wanted to try a new text editor so I tried Atom
- I code in Python ( As of now )
- I searched about this on other places but couldn't understand how those work.
- I use Windows

So, the issue - I wanted to be able to run Python code inside of the Atom program. I have downloaded Atom and the package needed for running code - script. Now I try to use the command that was given in order to execute my program. But well it gives some errors. These:

'python' is not recognized as an internal or external command,
operable program or batch file.
[Finished in 0.088s]
Test.py1:22
CRLFUTF-8Python

PIC:
![error](https://cloud.githubusercontent.com/assets/16853631/12531048/f2a91536-c223-11e5-946b-74439fc157d0.png)

When I searched online - I got various answers. Most of them said something like run Atom for 'terminal' and some mentioning to use 'atom' and 'atom.'. I have no idea what these terms are. Please tell me how to solve this error or how to use these ^^ methods. I am very new so don't expect me to know a lot.

**Comment by nixel2007** [comment]
Did you read [this part of readme](https://github.com/rgbkrk/atom-script#atom-cant-find-node--ruby--python--my-socks)?

**Comment by SamStrawbridge** [comment]
Hi, you may not have python installed on your machine, follow this guide if you haven't done so already http://docs.python-guide.org/en/latest/starting/install/win/

there is a fairly good free ide for python called komodo edit thttp://komodoide.com/komodo-edit/  Script isn't perfected yet and may have well mean that you come across some bugs, which will make you initial learning a fair bit harder, also script does not allow you to enter arguments like in a python repl so thats another reason to go and have a look at komodo edit, please don't be put off from using atom/script though :)

**Comment by Pranav-7** [comment]
I did read the readme thing but I don't understand how that works...
What does it mean by 'Make sure to launch Atom from the console/terminal' ?
I launch atom from the icon on my desktop and start menu.

Thanks for telling about Komodo Edit. I will try it but I wanted to use Atom...

**Comment by nixel2007** [comment]
@pranav-7 
1st variant 
* open dir with your project 
* press and hold left shift and right-click somewhere  in your dir (make sure you don't select a file) 
* chose "open command prompt here" 
* type `atom .` in new black window

2nd variant 
* press ctrl-r
* type `cmd`
* type `atom`

**Comment by Pranav-7** [comment]
@nixel2007 
Thanks a lot !
I still don't get the 1st variant but it worked with the 2nd one. I tried it and works.
Thanks a lot again.
