### ISSUE TITLE
Unable to find modules

### ISSUE THREAD

**Issue by goweiting** [rgbkrk/atom-script#753]
(new to atom)

i've defined a module Main.hs 

> >  module Main where
> > import TobeImport 
> > ...

and TobeImport.hs

> > module TobeImport where
> > ...

running the file using script causes the following error::

> > C:\Users\user\Documents\files\Main.hs:2:8:
> >    Could not find module `TobeImport'
> >    Use -v to see a list of the files searched for.
> > [Finished in 0.867s]

Is there a way to change the scope that script runs? or is it predetermined by ghci?

i'd tried running this using GHCI on emacs and cli and was able to load main.hs _and_ TobeImport.hs

**Comment by Stormherz** [comment]
@goweiting not quite familiar with haskell, but did you try running atom with `atom .` command from the directory, where you have Main.hs and TobeImport.hs?

**Comment by goweiting** [comment]
yeap. tried that as well.

Goh *Wei Ting*

_________________

"There are people in life you learn to live with,
there are people you know you can't live without,
and then there are people you know life wouldn't be the same *without*."
