### ISSUE TITLE
Killing infinite loops after closing script or Atom 

### ISSUE THREAD

**Issue by AhmedKamal20** [rgbkrk/atom-script#755]
**The Platform (Operating System) i'm on** : "Ubuntu 14.04.3 LTS"
**The Atom version i'm running** : 1.4.0
**The Script package version** : 3.4.1
**The Grammar i'm attempting to run** : Ruby

**Reproduction steps if possible** :
* Make Infinite Loops
* Run it with Script 
* Close Script "Esc"
* Close Atom 
* Go To Terminal , Run `$ top`
* The "ruby" process still there using the CPU 

**Why not killing the  process when i close "Script" ?**

**Comment by nixel2007** [comment]
For killing process you need to press other buttons 
https://github.com/rgbkrk/atom-script#command-and-shortcut-reference

**Comment by AhmedKamal20** [comment]
oh , sorry , i didn't notice

**Comment by AhmedKamal20** [comment]
@nixel2007 please close this issue :)
