### ISSUE TITLE
Got error when I try to run python code

### ISSUE THREAD

**Issue by kaktoos81** [rgbkrk/atom-script#765]
hi
i use windows 7 and i can not run python in atom
i use last version of atom and atom-script

http://s7.picofile.com/file/8236574826/error_atom.png

this error tells me that's python is not in my path while that is in my path
python 3.5.1
please help me
sorry for bad english

**Comment by JeffCohen** [comment]
Did you start Atom from the Windows command shell, or from double-clicking the icon on the desktop?

**Comment by kaktoos81** [comment]
double-clicking the icon on the desktop

**Comment by JeffCohen** [comment]
Yiu have to start Atom from the command line in order for it to know your PATH. 

That's what it says in your screenshot too.

**Comment by EntilZha** [comment]
If that doesn't work feel free to open issue back up.
