### ISSUE TITLE
JS: document is not defined workaround?

### ISSUE THREAD

**Issue by corysimmons** [rgbkrk/atom-script#766]
```js
const foo = document.querySelector('.foo')
```

throws a `document is not defined` err.

Is there any workaround for this? I make a lot of JS stuff for the browser and would love to use this package.

**Comment by rgbkrk** [comment]
The default JavaScript runtime is `node`, which doesn't have a `document`. You would need to rely on JSDom or something else to be able to use the `document` global. Even so, you're probably wanting to have your HTML as well, which wouldn't solve this issue for you.

**Comment by corysimmons** [comment]
I wonder if there's some clever way to grab that stuff by combining phantomjs and script..
