### ISSUE TITLE
Support built-in variables or context access in "configure run options"

### ISSUE THREAD

**Issue by nixel2007** [rgbkrk/atom-script#788]
AFAIK you can't add a command argument like "-check {FILE_PATH}", so you need to create profile/edit run options for every script you try to run

**Comment by nixel2007** [comment]
The estimated list is:
* {FILE_ACTIVE} - Full path to the currently active file in Atom. E.g. /home/noseglid/github/atom-build/lib/build.js
* {FILE_ACTIVE_PATH} - Full path to the folder where the currently active file is. E.g. /home/noseglid/github/atom-build/lib
* {FILE_ACTIVE_NAME} - Full name and extension of active file. E.g., build.js
* {FILE_ACTIVE_NAME_BASE} - Name of active file WITHOUT extension. E.g., build
* {PROJECT_PATH} - Full path to the root of the project. This is normally the path Atom has as root. E.g /home/noseglid/github/atom-build

**Comment by artbear** [comment]
+1

**Comment by pchomik** [comment]
+1
