### ISSUE TITLE
package.json parse error on master

### ISSUE THREAD

**Issue by Chosko** [rgbkrk/atom-script#800]
missing comma... this is the commit https://github.com/rgbkrk/atom-script/commit/23127191dddd7a25c9073e6b2e7299e5bce010fa

**Comment by rgbkrk** [comment]
Thank you.

**Comment by rgbkrk** [comment]
@fscherwi and @Chosko thanks for fixing bugs and adding new features.

Let's always make PRs with these instead of going straight to master, I'll do the same. The only commits that should get pushed directly are those from running `apm publish {semverUpdate}`.

**Comment by Chosko** [comment]
Yep! For this time I pushed it to master because It was a very simple syntax error that was breaking everything. I just thought "Hey... better push this fix now before it get released!".

However, I'll always make PRs. Pushes to master are evil, I agree!. ;-)

**Comment by rgbkrk** [comment]
:dancer: 

It's ok to merge your own PR for a fix like this too, I appreciate the steadfastness in fixing blocking issues.
