### ISSUE TITLE
Unable to install Script

### ISSUE THREAD

**Issue by mkaniok** [rgbkrk/atom-script#824]
Unable to install Script
->
Installing “script@3.5.2” failed.Hide output…

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\martin.kaniok\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\martin.kaniok\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\martin.kaniok\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository 'C:\Users\martin.kaniok\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=C:\Users\martin.kaniok\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\martin.kaniok\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\martin.kaniok\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\martin.kaniok\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.252.129]: errno=No error
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\martin.kaniok\\AppData\\Local\\atom\\app-1.5.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\martin.kaniok\\AppData\\Local\\atom\\app-1.5.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\martin.kaniok\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\martin.kaniok\\.atom\\.apmrc" "install" "C:\\Users\\MARTIN~1.KAN\\AppData\\Local\\Temp\\d-116214-11336-1qgtxjw\\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\martin.kaniok\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=No error
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by mkaniok** [comment]
dupl: Failed Atom install #820

**Comment by avonmoll** [comment]
I'm getting this same error - always related to the package `node-simple-plist`. The answer to #820 simply states that you need Git. I have Git installed and on my path; no application is having trouble accessing Git.

I've tried cloning the referenced repository (www.github.com/monsterkodi/node-simple-plist) and running `apm install` (kind of a shot in the dark, I know). I couldn't find a way to manually install this package and I don't even know which package depends on it. 

Does anyone know how I can install `node-simple-plist` manually such that `apm install script` doesn't attempt to pull from github?

**Comment by zander-smith** [comment]
I managed to get script to install by adding following to /etc/gitconfig (it switches git to use http protocol instead of git protocol):
[url "https://"]
	insteadOf = git://

**Comment by DemersM** [comment]
you can nstall node-simple-plist with npm 

`npm install simple-plist`
