### ISSUE TITLE
Can't run JS

### ISSUE THREAD

**Issue by ddulic** [rgbkrk/atom-script#826]
Any reason why I get this error?

Sorry for the noob question, new to JS.

Thank you in advance :)

![screen shot 2016-03-14 at 22 12 51](https://cloud.githubusercontent.com/assets/10076428/13760175/0d997f44-ea32-11e5-9bc4-a1aedaa1f1db.png)

**Comment by nixel2007** [comment]
There is no "document" property in atom runtime, cause atom work in nodejs environment

**Comment by nixel2007** [comment]
but you still can use console.log()

**Comment by ddulic** [comment]
Thanks @nixel2007 for the reply. Why way to change the runtime? Would be amazing if it would work :)

**Comment by rgbkrk** [comment]
We can't run browser based scripts in atom-script, it can only run on available interpreters. Our default JS runtime is [node.js](https://nodejs.org/).
