### ISSUE TITLE
python can't run sklearn module properly

### ISSUE THREAD

**Issue by wzhan366** [rgbkrk/atom-script#839]
I can't run a python script using 'script' cause the 'can't import a module', while I run the script on terminal directly, it runs smoothly.
The module is python- sklearn which is a sub-module of scipy

**Comment by nixel2007** [comment]
Try to setup a "working directory" property in run-options

**Comment by nixel2007** [comment]
Working directory is set to project path by default. Maybe your script need to be runned from other dir

**Comment by wzhan366** [comment]
I tried it and it works. Thanks!
