### ISSUE TITLE
Always first project folder as execution path

### ISSUE THREAD

**Issue by Cilenco** [rgbkrk/atom-script#878]
For example lets say all my java files (and packages) are in `/home/dev/Java/Project1/src/` and I add `src` as project folder in atom all works great. Packages, files, etc. are found correctly and the project compiles successfully.

If I open a second project (with same configuration as Project1) it doesn't work because the first project folder from atom is used as the java execution directory. So script looks in `Project1/src` for my files from Project2 (instead of `Project2/src`) and so it can't find all the files, packages, etc. If I close the first project folder in atom it works great again.

So the plugin uses always the first project folder in atom as execution path and does not search dynamically for the right project folder of the current file.

**Comment by nixel2007** [comment]
Hello, @Cilenco 
Thanks for the issue. This feature is WIP. I hope we can release it soon.

**Comment by Cilenco** [comment]
Oh okay thank you haven't found that.
I'm really looking forward for that release.
