### ISSUE TITLE
Cannot run scala scripts with '.scala' extension, cannot select scala as language

### ISSUE THREAD

**Issue by evanbiederstedt** [rgbkrk/atom-script#889]
I am trying to run Scala with a simple script `filename.scala` (and also `filename.sc`, as this extension is also allowed.)

I receive the error: 

    You must select a language in the lower right, or save the file with an appropriate extension.

So, I search for "Scala" under "Plain Text". The output is "No matches found". 

I believe I am using the most up-to-date version, and I do not see any guidelines in the documentation. Perhaps I'm missing something.

**Comment by nixel2007** [comment]
Did you install Scala language package?

**Comment by evanbiederstedt** [comment]
'language-scala' is installed with 'apm install language-scala'

I currently have 'Scala version 2.11.7' installed. 

I suspect I need to change a path somewhere....?

**Comment by evanbiederstedt** [comment]
I should add, I also tried to use `Script: Run Options` as noted in the documentation to run scala scripts. 

Given that I can run scala in the command line with `$ scala`, which outputs 

    Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_65).

I thought one could simply configure `script` with the command `scala`. Unfortunately, that doesn't work either.

**Comment by nixel2007** [comment]
Did you chose the "Scala" syntax in lower right?
It must work without script options.

**Comment by evanbiederstedt** [comment]
As I mentioned, I do not see "Scala" in the lower right. 

At the moment, it says "Plain Text". I click on this icon. A database search pops up. I search "Scala". There are no matches found.

**Comment by nixel2007** [comment]
looks like something is wrong with you language-scala installation. i've just installed it through atom itself, and i see a "scala" in languages list

**Comment by evanbiederstedt** [comment]
After re-installing via the command line and with the app, it appears to work now. 

Thank you for the help. Feel free to close.

**Comment by nixel2007** [comment]
Glad to help
