### ISSUE TITLE
Add support for Ansible YAML executable playbook.

### ISSUE THREAD

**Issue by applelight** [rgbkrk/atom-script#894]
It would be nice when a Ansible Playbook start with this line:
#!/usr/bin/env ansible-playbook playbook.yml

That the script module execute it.

**Comment by mattddowney** [comment]
https://github.com/rgbkrk/atom-script/pull/899

**Comment by rgbkrk** [comment]
Closing since there's _a_ way, though if we should re-open as a statement on `#!` lines feel free!

**Comment by applelight** [comment]
This is what I was looking for. Didn't knew you could set another "subset" of a YAML. Thanks!

**Comment by Java4Two** [comment]
Sorry to bring this back, but how exactly do you make this work? I'm relatively new to Atom.

**Comment by wireless00** [comment]
Geeeee. This one is back from the dead..... lol
Trying to wrap my head around it back again....

If I recall correctly,

You can create a normal playbook file and at the top, add this -->
!/usr/bin/env ansible-playbook playbook.yml

This would run the playbook file that you are within like a script that can be started by just running
./playbook.yaml
