### ISSUE TITLE
wrong command path on windows7

### ISSUE THREAD

**Issue by cdsama** [rgbkrk/atom-script#926]
I 'm using atom-script package for lua. My lua.exe is at c:/windows/system32/lua.exe，and it's works well with cmd.exe. But when I  run code in atom，it always says that 'lua' is not a command blah blah. 
Once I tried put the lua.exe file to the project folder,it worked and showed the result!So I guess that the plugin may not get the correct path environment variable and used the project path.

**Comment by Vlek** [comment]
Please learn what path variables are and how to properly use them. What you said made me cry on the inside. http://www.computerhope.com/issues/ch000549.htm
