### ISSUE TITLE
No GitHub connection for download, unique to this package

### ISSUE THREAD

**Issue by loschtreality** [rgbkrk/atom-script#944]
Hello, 

I recently executed a reinstall of Atom due to an original improper installation (yes, I’m still a beginner) and have had issues adding  _Script_  to my packages. I keep getting an error connecting to GitHub and it is unique to this package. If it helps, these are the commands I used:

[Uninstall Atom](https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/12)

```
1. Delete the app from the Applications folder
2. rm -rf ~/.atom
3. rm /usr/local/bin/atom
4. rm /usr/local/bin/apm
5. rm ~/Library/Preferences/com.github.atom.plist
6. rm ~/Library/Application Support/com.github.atom.ShipIt
7. rm -rf ~/Library/Application Support/Atom/
```

I originally tried downloading Script through the Atom application and got the error listed below. I then restarted my computer, then tried running `apm install Script` and got the same error listed below. I do my work at a public library and have been able to download my other packages/themes without issue and even push/pull from GitHub with the wifi here, not sure if I should try a different location.

Operating system: Mac OSX El Capitan 10.11.5 (15F34)

Atom    : 1.7.4
Electron: 0.36.8
Node    : 5.1.1
Script : 3.7.3 (attempting to download)

I read through other open issues regarding this error for previous versions of Script, but none of them have been closed. It seems like this is the closest to my current issue:

[Issue 820](https://github.com/rgbkrk/atom-script/issues/820)

I checked my system preferences and my firewall is **currently switched off**

```
npm ERR! git clone --template=/Users/michaelloschiavo/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /Users/michaelloschiavo/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository '/Users/michaelloschiavo/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=/Users/michaelloschiavo/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /Users/michaelloschiavo/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=/Users/michaelloschiavo/.atom/.apm/_git-remotes/_templates --mirror git://github.com/monsterkodi/node-simple-plist.git /Users/michaelloschiavo/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.252.121]: errno=Operation timed out
npm ERR! Darwin 15.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/michaelloschiavo/.atom/.apm/.apmrc" "--userconfig" "/Users/michaelloschiavo/.atom/.apmrc" "install" "/private/var/folders/n5/mz22yx7n1g313ymlh0tm9w6r0000gn/T/d-116424-548-1xkxlqe/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/Users/michaelloschiavo/.atom/.apm/_git-remotes/git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.121]: errno=Operation timed out
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/n5/mz22yx7n1g313ymlh0tm9w6r0000gn/T/apm-install-dir-116424-548-1r0fryz/npm-debug.log 
```

**Comment by vmuriart** [comment]
same as #881 ?

**Comment by loschtreality** [comment]
The user whom had the same problem as I (DemersM) was running Windows, I'm running OSX. Though the bottom line error of `fatal: unable to connect to github.com: github.com[0: 192.30.252.121]: errno=Operation timed out ` was the same, the earlier parts of the error message were different. Enlighten me if I'm wrong, but the errors do look different excluding the line I posted.

**Comment by loschtreality** [comment]
Not sure why this worked, but I was able to download script from the Atom application from my house instead of the public library and everything is working properly. Does anybody know why this occurred?

**Comment by vmuriart** [comment]
No idea. Still failing for me. I noticed that in the last few hours there was an update released maybe that helped?

**Comment by vmuriart** [comment]
figured out my issue as well. had to remove all my proxy settings, and use a non-firewall connection to install it.

**Comment by loschtreality** [comment]
Alright, then its concluded that that a firewall and/or proxy settings were the issues occurring with these cases. In order to fix it, one must change their firewall settings or connect to a network which will allow an unprotected download. My guess is that the firewall sees the word "script" which may be categorized as suspicious and denies the connection.

**Comment by rgbkrk** [comment]
Wow that's pretty wacky. I wonder if it's trying to clone over SSH or HTTP and the proxy munges it?

**Comment by vmuriart** [comment]
Its something about specifying a specific commit as the requirement. When it tries to acquire those packages the proxy settings get messed up somehow when behind the firewall. 
`npm` has an issue with having proxy env. variable setup even if they aren't needed to access the internet. 

That's why (in my case) it didn't work either when i was behind the firewall or when i was outside of it. Behind the firewall my proxy settings got messed up and couldnt download the requirements, outside the firewall npm failed to connect altogether.

**Comment by vmuriart** [comment]
The rather difficult part was realizing that this was an issue with the firewall/proxy. When I was initially installing this package through `Atom` it was reporting the issue to be that i didn't have `git` installed. I only saw the actual issue when i tried `apm install script`
