### ISSUE TITLE
Selection based run for Python not working

### ISSUE THREAD

**Issue by ghost** [rgbkrk/atom-script#955]
For some reason, I can't get the selection based run to work with Python 3.5.1 (Windows 10, Atom 1.7.4, script 3.7.3). Executing the entire file works fine but when selecting the entire file, it only executes the first line. 
When I try to execute selections somewhere in the script, it only gives me the running time and no output (no error either).
I tried the same thing with R and it seems to work fine. 
Any solutions would be super helpful, thanks!

**Comment by lui-habl** [comment]
for me the same

**Comment by urmigg** [comment]
Still the same issue on win10/Atom 1.11.2 / script 3.11.1

**Comment by rcassani** [comment]
Same here Win10, Atom 1.12.3,  Script 3.11.1

**Comment by MaxStreese** [comment]
Still not working - Win 10, Atom 1.12.7, Script 3.13.0

Is there any information about the progress on this? Will it be fixed eventually? :see_no_evil:

**Comment by rgbkrk** [comment]
For Python users, I highly recommend using [Hydrogen](https://github.com/nteract/hydrogen) which uses an IPython kernel underneath for an interactive session. I spend more time maintaining Hydrogen and nteract than I do this package.
