### ISSUE TITLE
Errors when running a matlab code

### ISSUE THREAD

**Issue by Dan-X** [rgbkrk/atom-script#975]
Cannot run a Matlab code. Errors like:

> This functionality is no longer supported under the -nojvm startup option. For more information, see "Changes to -nojvm Startup Option" in the MATLAB Release Notes. To view the release note in your system browser, run  web('http://www.mathworks.com/help/matlab/release-notes.html#btsurqv-6', '-browser').
Error using figure
This functionality is no longer supported under the -nojvm startup option. For more information, see "Changes to -nojvm Startup Option" in the MATLAB Release
Notes. To view the release note in your system browser, run  web('http://www.mathworks.com/help/matlab/release-notes.html#btsurqv-6', '-browser').

> Error in getnicedialoglocation (line 18)
    convertData.hFig = figure('visible','off');

> Error in questdlg (line 140)
FigPos    = getnicedialoglocation(FigPos, get(0,'DefaultFigureUnits'));

> Error in finish (line 1)
button = questdlg('Ready to quit?', ...

In the release note (2013a) i found that:

> Removal of Handle Graphics support under -nojvm startup option 
When you start MATLAB with the -nojvm startup option, Handle Graphics® functionality is not supported. (The -nojvm option is available for UNIX® platforms; see background information on the matlab (UNIX) reference page.)
Some aspects of MATLAB and related products use Handle Graphics in a way that might not be obvious. This includes anything that is based on or works using figures in MATLAB. Here is a summary of the affected features:
Creating figures and performing plotting tasks, such as using the plot, axes, getframe, and gcf functions.
Printing figures and using related functions such as print, hgexport, and saveas.
Creating GUIs in MATLAB using GUI-building functions such as warndlg.
Using Simulink® scopes and printing Simulink models.
If you use the -nojvm startup option and use Handle Graphics functionality, MATLAB produces an error.
......

> If you have been using the -nojvm startup option to work in a command line environment or because you do not use the MATLAB desktop, use the -nodesktop startup option instead.
If you have been using the -nojvm startup option because of memory or performance benefits, look for other ways to gain those improvements when you start MATLAB without the -nojvm option. See topics in Performance and Memory.
If you want to continue to use the -nojvm startup option, remove the code that is now producing the warnings.

Thank you!

**Comment by chris-hld** [comment]
Try to remove the matlab '-nojvm', option from file "lib/grammars.coffee" (line 355 and 358). Solved it for R2016a / Ubuntu 16.04.

**Comment by bremme** [comment]
I just created a pull request #995 which add support for using MATLAB's graphical capabilities, for example plot windows. Until the pull request gets accepted, you can change the `lib/grammars.coffee` file like this: 

```coffee
  MATLAB:
    "Selection Based":
      command: "matlab"
      args: (context) ->
        code = context.getCode()
        tmpFile = GrammarUtils.MATLAB.createTempFileWithCode(code)
        ['-nodesktop','-nosplash','-r',"try, run('" + tmpFile + "');while ~isempty(get(0,'Children')); pause(0.5); end; catch ME; disp(ME.message); exit(1); end; exit(0);"]
    "File Based":
      command: "matlab"
      args: (context) -> ['-nodesktop','-nosplash','-r',"try run('" + context.filepath + "');while ~isempty(get(0,'Children')); pause(0.5); end; catch ME; disp(ME.message); exit(1); end; exit(0);"]
```

**Comment by nixel2007** [comment]
:ship: 3.9.0

**Comment by monajalal** [comment]
@bremme  can you please have a look at this question? http://stackoverflow.com/questions/39520317/matlabthis-functionality-is-no-longer-supported-under-the-nojvm-startup-optio

**Comment by bremme** [comment]
@monajalal Sorry for my delayed reply. I guess you already managed to solve this problem, if not let me know.
