### ISSUE TITLE
How to solve "unable to run node" error

### ISSUE THREAD

**Issue by lincolnfrias** [rgbkrk/atom-script#978]
I finally found a solution to when the following problem happens even running atom from the terminal:

> Unable to run
> node
> Did you start Atom from the command line?
> atom .
> Is it in your PATH?

In my case (Linux, Ubuntu), the solution was to install node-legacy besides nodejs. I just did:
`sudo apt install  node-legacy`

**Comment by XalYU** [comment]
I didn't found node-legacy so I used nodejs-legacy and it worked
