### ISSUE TITLE
Add support for HTML

### ISSUE THREAD

**Issue by genkitakeichi** [rgbkrk/atom-script#998]
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="questionnaire.css">
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="questionnaire.js"></script>

</head>
<body>

<div class="article">
    <h1>質問紙</h1>
    <?php print htmlspecialchars($error_message); ?>
    <form method="POST" id="form1" action="thanks.php">
        <?php foreach($data as $value):  ?>

            <?php for($i=1; $i <= 10; $i++){ ?>
                <div id="no-margin" <?php if ($i%2===0) { print "class='color'"; } ?>>
                    <p id="no-margin"><?php print $value['Q'.$i]; ?></p>  
                    <label><input type="radio" value="5" name="<?php print htmlspecialchars($i) ?>" >とてもそう思う</label>
                    <label><input type="radio" value="4" name="<?php print htmlspecialchars($i) ?>" >そう思う</label>
                    <label><input type="radio" value="3" name="<?php print htmlspecialchars($i) ?>" >わからない</label>
                    <label><input type="radio" value="2" name="<?php print htmlspecialchars($i) ?>" >あまりそう思わない</label>
                    <label><input type="radio" value="1" name="<?php print htmlspecialchars($i) ?>" >全くそう思わない</label>
                </div>
            <?php } ?>

        <?php endforeach ?>
        <div id="button">
            <input type="submit" name="btn" id="btn" value="回答を送信">
        </div>
        <div id="box"></div>
    </form>
</div>

</body>
</html>

**Comment by BladeMight** [comment]
Translation of above(seems useless):
# Questionnaire
>
I think that what i think will not change, but i don't think that this is too much, though i dont think quite so.

**Comment by andyrichardson** [comment]
Duplicate #330. Please check existing open/closed issues before posting your own.
